// Generated by scripts/update-official-color-catalog.ps1 on 2026-08-03.
// Values are exact digital swatches published in the linked manufacturer product pages.
package com.canvault.app.data

import java.text.Normalizer

data class OfficialCanColorSource(
    val id: String,
    val label: String,
    val url: String,
    val extractedShadeCount: Int,
)

data class OfficialCanColor(
    val lineId: String,
    val colorName: String,
    val colorCode: String?,
    val productCode: String?,
    val hex: String,
    val sourceId: String,
)

object OfficialCanColorCatalog {
    const val publishedAt = "2026-08-03"
    const val accuracyNote = "Digitaler Herstellerwert; Lack kann je nach Untergrund, Licht und Display abweichen."

    val sources = listOf(
        OfficialCanColorSource("mtn-94", "MTN Shop Deutschland", "https://www.mtn-shop.de/mtn-94-ex0140241m", 217),
        OfficialCanColorSource("mtn-hardcore", "MTN Shop Deutschland", "https://www.mtn-shop.de/mtn-hardcore", 142),
        OfficialCanColorSource("mtn-water-based", "MTN Shop Deutschland", "https://www.mtn-shop.de/mtn-water-based-400", 83),
        OfficialCanColorSource("mtn-mega", "MTN Shop Deutschland", "https://www.mtn-shop.de/mtn-mega-colors", 16),
        OfficialCanColorSource("mtn-vice", "MTN Shop Deutschland", "https://www.mtn-shop.de/mtn-vice-ex014vi0009", 50),
        OfficialCanColorSource("montana-black", "Montana Cans", "https://www.montana-cans.com/de/Montana-BLACK-400ml/263507", 181),
        OfficialCanColorSource("montana-black-infra", "Montana Cans", "https://www.montana-cans.com/de/Montana-BLACK-400ml-Infra-Colors/352249", 6),
        OfficialCanColorSource("montana-gold-colors", "Montana Cans", "https://www.montana-cans.com/de/Montana-GOLD-400ml-Colors/284502", 193),
        OfficialCanColorSource("montana-gold-transparent", "Montana Cans", "https://www.montana-cans.com/de/Montana-GOLD-400ml-Transparent-Colors/419362", 9),
        OfficialCanColorSource("montana-gold-fluorescent", "Montana Cans", "https://www.montana-cans.com/de/Montana-GOLD-400ml-Fluorescent-Colors/521409", 8),
        OfficialCanColorSource("montana-gold-chrome", "Montana Cans", "https://www.montana-cans.com/de/Montana-GOLD-400ml-Chrome-Effect-Colors/285936", 3),
        OfficialCanColorSource("montana-gold-metallic", "Montana Cans", "https://www.montana-cans.com/de/Montana-GOLD-400ml-Metallic-Colors/369759", 2),
        OfficialCanColorSource("montana-ultra-wide", "Montana Cans", "https://www.montana-cans.com/de/Montana-ULTRA-WIDE-750ml/486968", 12),
        OfficialCanColorSource("molotow-premium", "Molotow Onlineshop", "https://shop.molotow.com/produkt/molotow-premium/", 240),
        OfficialCanColorSource("molotow-burner", "Molotow Onlineshop", "https://shop.molotow.com/produkt/burner-spraydose/", 1),
        OfficialCanColorSource("flame-blue", "Molotow Onlineshop", "https://shop.molotow.com/produkt/flame-blue/", 115),
        OfficialCanColorSource("flame-orange", "Molotow Onlineshop", "https://shop.molotow.com/produkt/flame-orange/", 133),
        OfficialCanColorSource("molotow-coversall", "Molotow Onlineshop", "https://shop.molotow.com/produkt/coversall-color/", 1),
        OfficialCanColorSource("loop-400", "Loop Colors", "https://loopcolors.com/product/loop-400ml/", 218),
        OfficialCanColorSource("loop-asphalt-600", "Loop Colors", "https://loopcolors.com/product/asphalt-600-ml/", 1),
        OfficialCanColorSource("loop-asphalt-400", "Loop Colors", "https://loopcolors.com/product/asphalt-400ml/", 1),
        OfficialCanColorSource("ironlak-400", "Ironlak", "https://ironlak.com/product/ironlak-acrlyic-spray-paint-400ml/", 101),
        OfficialCanColorSource("double-a", "Double A Spraypaint", "https://doublea-spraypaint.com/products/double-a-spraypaint-400ml-143-farben", 143),
    )

    private data class RawBlock(val sourceId: String, val lineId: String, val rows: String)

    private val rawBlocks = listOf(
        RawBlock("double-a", "double-a:double-a", """
            Black|DA-100||#000000
            White|DA-102||#FFFFFF
            Graphite|DA-104||#1F252A
            Railway|DA-106||#2C2E2F
            Anonymous|DA-108||#484848
            Cement|DA-110||#656566
            Stingray|DA-112||#84858A
            Shadow|DA-114||#929398
            Fog|DA-116||#A3A4A8
            Pebble|DA-118||#C7C7C9
            Chocolate|DA-120||#351C1D
            Chestnut|DA-122||#312724
            Mocca|DA-124||#412E23
            Moccachino|DA-126||#5D3B19
            Caramel|DA-128||#724C20
            Peanut|DA-130||#A77A27
            Cappuchino|DA-132||#DBBB73
            Tortilla|DA-134||#EBD69E
            Ivory|DA-136||#F0E8C2
            Moss|DA-138||#353E2F
            Strong Mustard|DA-140||#454D25
            Mustard|DA-142||#676726
            Dijon|DA-144||#6F7223
            Yolk|DA-146||#898C28
            Pine|DA-148||#364E30
            Strong Verdigis|DA-150||#4A6B41
            Verdigris|DA-152||#62875D
            Toronto Collective Verdigis|DA-154||#74956D
            Strong Sage|DA-156||#88A481
            Sage|DA-158||#93AD8E
            Light Sage|DA-160||#ACC3A7
            Green|DA-162||#208035
            Gleis 8 Green|DA-164||#1B9838
            Krazy 8 Green|DA-166||#3C9339
            Made Fresh Green|DA-168||#56AF34
            No Name´s Green|DA-170||#0D4F34
            Mad Green|DA-172||#84BF5C
            Pistacchio|DA-174||#91C46D
            Light Pistacchio|DA-176||#C1D7AB
            Emerald|DA-178||#0F6B50
            Malachit|DA-180||#1C7949
            Jade|DA-182||#168962
            Demain j'arrête Peppermint|DA-184||#21A77B
            Lowbrow Peppermint|DA-186||#3EAF89
            Aquamarin|DA-188||#A4D1A9
            Graffitibox Peppermint|DA-190||#69BEB1
            Schiefdruff Peppermint|DA-192||#7DC6B4
            Opal|DA-194||#B8DFE0
            Ghettolove Ocean|DA-196||#05374C
            Atlantis|DA-198||#0B4E6D
            Backyard Ocean|DA-200||#13668C
            New Chrome|DA-2001||#B5B4B4
            Carribean|DA-202||#0B7CA3
            Maldives|DA-204||#117791
            Strong Arctic|DA-206||#1F4961
            Arctic|DA-208||#275D7B
            Pastel Arctic|DA-210||#376484
            Ice Blue|DA-212||#B1D3F1
            Galaxy|DA-214||#1F212D
            Saphire|DA-216||#1A2037
            Artchemia Galaxy|DA-218||#1E274A
            Deep Sea|DA-220||#11336D
            Bermuda|DA-222||#12387D
            760 Supplies Blue|DA-224||#1C3F83
            Mad Flava Blue|DA-226||#0E559E
            Full Color Blue|DA-228||#1E71B8
            Backjump Blue|DA-230||#5693CF
            Baby Blue|DA-232||#A1C9E7
            Sky Blue|DA-234||#A7DAF7
            Light Sky Blue|DA-236||#B3D6F2
            Elevated Purple|DA-238||#2A1A41
            Get Lost A Lot Purple|DA-240||#352253
            Aster|DA-242||#4D3C8C
            Amethyst|DA-244||#5A5096
            Grape|DA-246||#7E75B5
            Art Bench Grape|DA-248||#7D79B8
            Lavender|DA-250||#A39ECE
            Mauve|DA-252||#CCCBE4
            Light Mauve|DA-254||#C0BBDE
            Baby Pink|DA-256||#9571A5
            Scrapyard Blue|DA-258||#2B2951
            Rec Shop Blue|DA-260||#28376E
            Oink Art Blue|DA-262||#324181
            Strong Purple|DA-264||#532E73
            Aubergine|DA-266||#521835
            Strong Viola|DA-268||#331638
            Beatlab Violet|DA-270||#2E1B42
            Power Violet|DA-272||#3F2358
            Violet|DA-274||#663A7B
            Pantograff Violet|DA-276||#6E488D
            Light Violet|DA-278||#864F95
            Dark Fig|DA-280||#7A2453
            Fig|DA-282||#6F1D4B
            Strong Mistyrose|DA-284||#7A3162
            Mistyrose|DA-286||#8A3469
            Light Mistyrose|DA-288||#CB78A8
            Strong Cadillac|DA-290||#7A71B2
            Cadillac|DA-292||#AEA2CF
            Light Cadillac|DA-294||#CDBFDF
            Rasberry|DA-296||#9F1866
            Escapizm Pink|DA-298||#A41641
            Light Raspberry|DA-300||#AD3886
            Transparent Black|DA-3000||#615D5E
            Transparent White|DA-3002||#FAFCFA
            Soultunes Pink|DA-302||#B3184C
            Elita Graff Pink|DA-304||#DD6B98
            All City Legends Pink|DA-306||#AF4990
            Fat-Cap Pink|DA-308||#BC6DA9
            14th Street Pink|DA-310||#CB8EBE
            Light Piggy Pink|DA-312||#D6A2CA
            Beach|DA-314||#F9D2E2
            Terracotta|DA-316||#CB8179
            Blush Pink|DA-318||#E08A84
            Light Blush Pink|DA-320||#E0A6A9
            Power Beach|DA-322||#EDA7A6
            Teint|DA-324||#CD9691
            Light Teint|DA-326||#F7C59F
            Rosy|DA-328||#EAAF96
            Peach|DA-330||#F8B796
            Eggshell|DA-332||#FAE1E1
            Meat Loaf|DA-334||#562029
            Madriz 24/7 Red|DA-336||#C95657
            Scarlet|DA-338||#B31D26
            Dedicated Red|DA-340||#9F1E29
            Momentum Red|DA-342||#7F241C
            La Underground Red|DA-344||#941515
            Damagers Red|DA-346||#BE1921
            Melon|DA-348||#F09462
            Light Melon|DA-350||#EF8948
            Coral|DA-352||#E4625F
            Pink Coral|DA-354||#CF4160
            Stgt Haubi Orange|DA-356||#EB6011
            Amber|DA-358||#B33747
            Peachy|DA-360||#B25021
            Apricot|DA-362||#F59E5E
            Dosen Späti Orange|DA-364||#E77B3E
            Pastel Orange|DA-366||#EE732B
            Supreme Yellow|DA-368||#EAB13C
            The Hangout Yellow|DA-370||#FCE51F
            Colors & Corner Yellow|DA-372||#FCEB4E
            Mad Yellow|DA-374||#FCF074
            Light Yellow|DA-376||#FBF39B
            Blonde|DA-378||#F7F4E5
        """.trimIndent()),
        RawBlock("flame-blue", "flame:flame-blue", """
            vanille|FB-100|557001|#F0DF82
            fluogelb|FB-1000|557165|#F6E600
            fluoorange|FB-1002|557166|#EC6600
            fluopink|FB-1004|557167|#E50076
            fluogrün|FB-1006|557168|#36AA32
            zinkgelb|FB-102|557002|#FEDD3B
            kadmiumgelb|FB-104|557003|#FAD920
            signalgelb|FB-106|557004|#F5CD04
            melonengelb|FB-110|557006|#F6BD00
            safran|FB-112|557007|#FBBE5C
            dahlien|FB-114|557008|#FBBD41
            pfirsich|FB-200|557017|#FCB476
            pastellorange|FB-202|557018|#FA9127
            hellorange|FB-204|557019|#E97500
            pfirsich kalt|FB-208|557021|#F1D6B6
            aprikose|FB-210|557022|#F28749
            orange|FB-212|557023|#D65527
            orangerot|FB-214|557024|#D3451E
            signalrot|FB-304|557027|#D83431
            rubinrot|FB-306|557028|#C40A35
            schweinchenrosa hell|FB-308|557029|#ED9CAE
            schweinchenrosa|FB-310|557030|#E64461
            crazy cherry|FB-311|557032|#BB2037
            feuerrot|FB-312|557031|#C03331
            kirsche dunkel|FB-313|557033|#9C052D
            verkehrsviolett dunkel|FB-318|557034|#3C043B
            burgundrot|FB-320|557035|#AA0028
            aubergine|FB-322|557036|#471F35
            erikaviolett hell|FB-399|557048|#D79FCA
            erikaviolett|FB-400|557037|#DD6A9C
            erika pastel|FB-401|557052|#E1BDCC
            telemagenta|FB-402|557038|#D8326C
            verkehrsviolett|FB-404|557039|#8A1478
            lavendel|FB-406|557040|#CBD2EB
            weintraube|FB-408|557041|#9466A2
            brombeere|FB-410|557042|#6C427C
            johannisbeere|FB-412|557043|#4F3159
            veilchen pastell|FB-414|557044|#C6CEE6
            veilchen hell|FB-416|557045|#B9B6E9
            veilchen|FB-418|557046|#6167A2
            veilchen dunkel|FB-420|557047|#243B81
            kosmosblau hell|FB-424|557049|#6F7ACF
            kosmosblau|FB-426|557050|#374A9C
            kosmosblau dunkel|FB-428|557051|#001E60
            lightning blau|FB-502|557053|#B9D9EC
            lichtblau hell|FB-504|557054|#92C4E4
            lichtblau|FB-508|557056|#4496D1
            himmelblau|FB-510|557057|#006BB3
            signalblau|FB-512|557058|#075095
            echtblau|FB-514|557059|#1B4988
            cremeblau hell|FB-516|557060|#7FA8C5
            cremeblau|FB-518|557061|#2086C5
            cremeblau dunkel|FB-520|557062|#075A8E
            saphirblau|FB-522|557063|#0B2C59
            denimblau pastell|FB-524|557064|#B5D0EE
            denimblau hell|FB-526|557065|#93C3E1
            denimblau|FB-528|557066|#5088AE
            denimblau dunkel|FB-530|557067|#3D586E
            riviera hell|FB-600|557076|#B0E3E4
            riviera|FB-602|557077|#5CC9BA
            lagunenblau|FB-604|557078|#00A390
            ozeanblau|FB-606|557079|#007375
            aqua pastell|FB-614|557083|#8DDECC
            aqua hell|FB-616|557084|#3397B6
            aqua|FB-618|557085|#004E5A
            aqua dunkel|FB-620|557086|#004C46
            pistazie hell|FB-624|557088|#D7D43F
            pistazie|FB-626|557089|#BAC33D
            grasgrün|FB-628|557090|#89A945
            farngrün|FB-630|557091|#699848
            laubgrün|FB-632|557092|#4D8746
            moosgrün|FB-634|557093|#2E7043
            tannengrün|FB-636|557094|#245C4E
            kiwi pastell|FB-638|557095|#ECE819
            kiwi hell|FB-640|557096|#BAD64A
            kiwi|FB-642|557097|#7BBD2A
            kiwi dunkel|FB-644|557098|#649116
            frühlingsgrün|FB-654|557103|#C2E089
            tarzangrün|FB-656|557104|#93B379
            tarngrün|FB-658|557105|#71744F
            olive|FB-660|557106|#21372C
            menthol pastell|FB-662|557107|#C2DEBA
            menthol hell|FB-664|557108|#8BE1B2
            menthol|FB-666|557109|#6DCB99
            menthol dunkel|FB-668|557110|#004538
            türkis hell|FB-670|557111|#23A37D
            türkis|FB-672|557112|#008B5A
            türkis dunkel|FB-674|557113|#216144
            elfenbein hell|FB-702|557116|#EDDFB6
            beigebraun|FB-704|557117|#BF9B5C
            ocker|FB-706|557118|#9D682F
            nuss|FB-708|557119|#4C2900
            schokolade|FB-710|557120|#2B1104
            keksteig pastell|FB-716|557123|#F5E4D3
            keksteig|FB-717|557125|#D6CAA0
            macadamianuss pastell|FB-718|557126|#E6C3AC
            macadamianuss|FB-719|557127|#A58876
            graubeige hell|FB-732|557131|#B4A485
            graubeige|FB-734|557132|#A18B62
            khakigrau|FB-736|557133|#6F5B39
            dunkelbraun|FB-738|557134|#3B3024
            terracottagrau pastel|FB-808|557139|#C8B8B4
            terracottagrau hell|FB-810|557140|#A68A8A
            terracottagrau|FB-812|557141|#816A6B
            violettgrau mittel|FB-820|557145|#695D6C
            violettgrau|FB-822|557146|#56495A
            hellgrau neutral|FB-834|557152|#DAD3CC
            mittelgrau neutral|FB-836|557153|#B0ADAC
            grau neutral|FB-838|557154|#808080
            dunkelgrau neutral|FB-840|557155|#84807F
            anthrazitgrau mittel|FB-842|557156|#515250
            anthrazitgrau|FB-844|557157|#4A4B4E
            anthrazitgrau dunkel|FB-846|557158|#363636
            reinweiß|FB-900|557159|#FFFFFF
            tiefschwarz|FB-904|557161|#000000
        """.trimIndent()),
        RawBlock("flame-orange", "flame:flame-orange", """
            *NEU* FO-198 pfirsich mittel||558073|#FFC093
            *NEU* FO-303 pastellrot||558087|#E73C41
            *NEU* FO-305 koralle rot||558099|#E04D3D
            *NEU* FO-409 erikapink||558100|#DFACC2
            *NEU* FO-415 krocus||558186|#B4A5DC
            *NEU* FO-422 kosmosblau pastell||558101|#9DA8DE
            *NEU* FO-605 lagunenblau dunkel||558102|#009C8F
            *NEU* FO-615 crazy aqua||558187|#0BB5CB
            *NEU* FO-621 senf mittel||558143|#EABB00
            *NEU* FO-637 birne hell||558130|#C0A927
            *NEU* FO-639 birne||558138|#9F8C13
            *NEU* FO-641 birne dunkel||558144|#786522
            *NEU* FO-663 minze||558142|#97DDA8
            *NEU* FO-675 smaragd grün||558185|#005F3C
            *NEU* FO-703 milchkaffee||558147|#D7B38A
            vanille|FO-100|558001|#F0DF82
            zinkgelb|FO-102|558002|#FEDD3B
            kadmiumgelb|FO-104|558003|#FAD920
            signalgelb|FO-106|558004|#F5CD04
            melongelb hell|FO-107|558010|#F9B60C
            melonengelb|FO-110|558006|#F6BD00
            melone dunkel|FO-111|558005|#F7AD00
            curry|FO-113|558009|#F69C15
            pfirsich|FO-200|558017|#FCB476
            pastellorange|FO-202|558018|#FA9127
            hellorange|FO-204|558019|#E97500
            pfirsich kalt|FO-208|558021|#F1D6B6
            aprikose|FO-210|558022|#F28749
            orange|FO-212|558023|#D65527
            rotorange|FO-214|558024|#D3451E
            signalrot|FO-304|558027|#D83431
            rubinrot|FO-306|558028|#C40A35
            koralle|FO-307|558013|#E76966
            schweinchenrosa hell|FO-308|558029|#ED9CAE
            schweinchenrosa mittel|FO-309|558011|#E3647D
            schweinchenrosa|FO-310|558030|#E64461
            crazy cherry|FO-311|558032|#BB2037
            feuerrot|FO-312|558031|#C03331
            kirsch dunkel|FO-313|558033|#9C052D
            schweinchenrosa dunkel|FO-314|558014|#C40A35
            verkehrsviolett dunkel|FO-318|558034|#47233C
            burgundrot|FO-320|558015|#AA0028
            aubergine|FO-322|558036|#471F35
            aubergine dunkel|FO-323|558016|#2D2927
            violett|FO-396|558020|#9F5D9C
            crazy violett|FO-397|558025|#81487C
            tief violett|FO-398|558026|#684679
            erikaviolett hell|FO-399|558035|#DCA7C8
            erikaviolett|FO-400|558037|#DD6A9C
            erika pastell|FO-401|558052|#E1BDCC
            telemagenta|FO-402|558038|#D8326C
            tief violett dunkel|FO-403|558074|#4A284E
            verkehrsviolett|FO-404|558039|#8A1478
            erika pastell mittel|FO-405|558065|#CA94AC
            erikaviolett mittel|FO-407|558007|#BE628F
            weintraube|FO-408|558041|#9466A2
            brombeere|FO-410|558042|#6C427C
            johannisbeere|FO-412|558043|#4F3159
            veilchen hell|FO-416|558045|#B9B6E9
            veilchen|FO-418|558046|#6167A2
            veilchen dunkel|FO-420|558047|#243B81
            kosmosblau hell|FO-424|558049|#6F7ACF
            kosmosblau|FO-426|558050|#374A9C
            kosmosblau dunkel|FO-428|558051|#001E60
            lightning blau|FO-502|558053|#70C7E7
            lichtblau hell|FO-504|558054|#92C4E4
            lichtblau|FO-508|558056|#4496D1
            himmelblau|FO-510|558057|#006BB3
            crazy blue|FO-511|558070|#0089BF
            signalblau|FO-512|558058|#075095
            echtblau|FO-514|558059|#1B4988
            ultramarineblau|FO-515|558055|#002C5C
            cremeblau hell|FO-516|558060|#7FA8C5
            cremeblau|FO-518|558061|#2086C5
            cremeblau dunkel|FO-520|558062|#075A8E
            saphirblau|FO-522|558063|#0B2C59
            saphirblau dunkel|FO-523|558072|#232A3C
            grünspan hell|FO-531|558068|#8CB9B7
            grünspan mittel|FO-532|558069|#7CA6A5
            grünspan|FO-533|558071|#668E8E
            crazy riviera|FO-601|558075|#48B79D
            riviera|FO-602|558077|#5CC9BA
            lagunenblau|FO-604|558078|#00A390
            ozeanblau|FO-606|558079|#007375
            salbei mittel|FO-608|558080|#98ACA1
            salbei|FO-609|558081|#7DA48F
            salbei dunkel|FO-610|558082|#517765
            aqua pastell hell|FO-613|558086|#B7E8DE
            aqua pastell|FO-614|558083|#8DDECC
            aqua hell|FO-616|558084|#3397B6
            aqua|FO-618|558085|#004E5A
            Senf hell|FO-622|558122|#F0BC01
            crazy green|FO-623|558115|#DEDE2E
            pistazie hell|FO-624|558088|#D7D43F
            Senf|FO-625|558124|#C7A322
            crazy grass|FO-627|558121|#96B922
            grasgrün|FO-628|558090|#89A945
            saftgrün|FO-629|558629|#008834
            Senf dunkel|FO-631|558128|#A37F13
            laubgrün|FO-632|558092|#4D8746
            khakigrün|FO-633|558129|#836829
            tannengrün|FO-636|558094|#245C4E
            kiwi hell|FO-640|558096|#B7D048
            kiwi|FO-642|558097|#7BBD2A
            kiwi dunkel|FO-644|558098|#649116
            menthol hell|FO-664|558108|#8BE1B2
            menthol|FO-666|558109|#6DCB99
            crazy menthol|FO-667|558114|#6BB66C
            türkis hell|FO-670|558111|#23A37D
            türkis|FO-672|558112|#008B5A
            kakao hell|FO-697|558135|#D17F79
            kakao|FO-698|558136|#9D514B
            braunrot|FO-699|558137|#882626
            elfenbein hell|FO-702|558116|#EDDFB6
            beigebraun|FO-704|558117|#BF9B5C
            ocker|FO-706|558118|#9D682F
            nuss|FO-708|558119|#4C2900
            schokolade|FO-710|558120|#2B1104
            graubeige hell|FO-732|558131|#B4A485
            graubeige|FO-734|558132|#A18B62
            khakigrau|FO-736|558133|#6F5B39
            steingrau hell|FO-830|558148|#C8C8B5
            steingrau mittel|FO-831|558149|#989887
            steingrau|FO-832|558150|#737165
            steingrau dunkel|FO-833|558151|#403E35
            hellgrau neutral|FO-834|558152|#DAD3CC
            mittelgrau neutral|FO-836|558153|#B0ADAC
            dunkelgrau neutral|FO-840|558155|#84807F
            anthrazitgrau|FO-844|558157|#4C4C4F
            reinweiß|FO-900|558159|#FFFFFF
            thick black|FO-901|558158|#000000
            thick black (500 ml)|FO-901|558801|#000000
            tiefschwarz|FO-904|558161|#000000
        """.trimIndent()),
        RawBlock("ironlak-400", "ironlak:ironlak-400-ml", """
            Appliance White|||#FFFFFF
            Apsen (White)|||#FFFFFF
            Askew's Olivia|||#514E26
            Atlantic|||#336094
            Atmosphere|||#8FC6E7
            Autumn|||#D03238
            Banos Asbestos|||#9C842F
            Battleship|||#717271
            Boston|||#409C7E
            Bright Chrome|||#8B8C8D
            Butter|||#F6C55B
            Cameleon|||#62A744
            Cassius|||#C7B9AB
            Chicago|||#7E9ABF
            Cuppa|||#CFA075
            Delicious|||#F49EC4
            Earth|||#513528
            Eggplant|||#604776
            Electro|||#69CADA
            Eureka|||#FFB718
            Ewok's Froggy|||#949436
            Field|||#4C8B3F
            Flirt|||#E01382
            Fluoro Green|||#ACD58A
            Fluoro Orange|||#FF4500
            Fluoro Pink|||#CE008C
            Fluoro Red|||#F16D78
            Fluoro Yellow|||#FFE500
            Fraser|||#F2DFCD
            Frazetta|||#00B3AA
            Frostbite|||#D0D9E5
            Furious|||#AB6388
            Gold (Metallic)|||#A29061
            Guacamole|||#6D702E
            Guava|||#F06177
            Gypsy|||#C08CBE
            Halloween|||#D3441C
            Hitachi|||#B2B3B2
            Huey|||#1D5632
            Hunter|||#007277
            Irwin|||#E2C19D
            Isla Rose|||#BE3B4A
            Jarnte|||#45BC96
            Jurne's Micah|||#9F3122
            Keen|||#C5AB2E
            Knockout|||#96665C
            Lazy Grey|||#383935
            Lightning|||#00ABC7
            Linz Iceberg|||#58C2B6
            Marsh|||#6F5722
            Matador|||#8B0E04
            Matt Black|||#231F20
            Matt Clear Varnish|||#FFFFFF
            Meks Magic|||#C6B3D7
            Melbourne|||#545759
            Midnight|||#0F2C52
            Moberry|||#8D0B56
            Mocha|||#A0662C
            Mustard|||#E2CA30
            Neverland|||#004E58
            Nitro|||#F0E048
            Ogre|||#B2DDC9
            Ozone|||#BEE0EA
            Pacific|||#1B3C6D
            Panther|||#231B33
            Phantom|||#775BA6
            Pineapple Park|||#FFDD00
            Placid|||#ABDCD4
            Pose Sushi|||#9B268F
            Potion|||#EC80A8
            Prestige|||#931D28
            Prince|||#77246C
            Punk|||#B969AA
            Purple Reign|||#3D1951
            Reals Sublime|||#A3CF5E
            Reef|||#008DA8
            Roarke (Black)|||#000000
            Sasha|||#A49382
            Shamrock|||#71C6A6
            Sharon|||#7C6755
            Sirum Black-Red|||#571C1F
            Smoulder|||#DBD8D6
            Smurf|||#0076BB
            Sofles Violence / Violet|||#AE95C6
            Sorbet|||#FFFAC3
            Soviet True Red|||#C21F32
            Swiss|||#64340F
            Tango|||#FF9D6B
            Torquay|||#009ADD
            True Royal|||#005189
            Tues Afterburn|||#F58326
            Two Cents (Metallic Copper)|||#8E634A
            Vans Kryptonite|||#CDDC29
            Venom|||#4D2F47
            Vizie's Smiley Face|||#FFDB00
            Volcano|||#FF7E2E
            Wanyology Blood Orange|||#E53C2E
            Washington|||#8A8B8C
            Whip|||#FFBE9E
            Whizbang|||#D4E38E
            Yankee|||#172751
        """.trimIndent()),
        RawBlock("loop-400", "loop-colors:loop-400-ml", """
            WHITE|LP-100||#FFFFFF
            GLOSS WHITE|LP-101||#FFFFFF
            BLACK MATT|LP-103||#000000
            BLACK|LP-104||#000000
            BLACK GLOSS|LP-105||#000000
            MADRID|LP-106||#FBF193
            BARCELONA|LP-107||#FFEC65
            VALENCIA|LP-108||#FFDD00
            SEVILLA|LP-109||#FDCE07
            MALAGA|LP-110||#F9B300
            AMSTERDAM|LP-120||#F3991B
            HARLEM|LP-121||#E78010
            UTRECHT|LP-122||#EC6F07
            ROTTERDAM|LP-123||#BB4914
            EINDHOVEN|LP-124||#FFDCA3
            BREDA|LP-125||#F8B14C
            HELMOND|LP-126||#F2921F
            ROSENDHAL|LP-127||#EB6D0F
            ARNHEM|LP-128||#E75811
            TILBURG|LP-129||#E04D14
            OSS|LP-130||#E24415
            BRUSSELS|LP-131||#FF3300
            MANCHESTER|LP-136||#E33617
            LIVERPOOL|LP-137||#D33118
            NEWCASTLE|LP-138||#BE2C1C
            YORK|LP-139||#A6241C
            LEEDS|LP-140||#7B1417
            CAMBRIDGE|LP-141||#4E0F0F
            DERBY|LP-142||#E8586D
            BRISTOL|LP-143||#E53049
            BRIGHTON|LP-144||#DA0531
            OXFORD|LP-145||#963034
            LONDON|LP-146||#330000
            BIRMINGHAM|LP-147||#FF6699
            NOTTINGHAM|LP-148||#EF7C71
            WARSAW|LP-149||#B50156
            DUBLIN|LP-150||#FAEDE2
            GALWAY|LP-151||#F5B9A6
            DUNDALK|LP-152||#EE847F
            WATERFORD|LP-153||#BD4140
            LIMERICK|LP-154||#F8CBCD
            SWORDS|LP-155||#E7A4A9
            CORK|LP-156||#8F443C
            SLIGO|LP-157||#CC727C
            FARO|LP-158||#F4B2C1
            BEJA|LP-159||#F095A7
            COIMBRA|LP-160||#E85A82
            PORTO|LP-161||#C63D65
            AMADORA|LP-162||#9E174F
            LISBOA|LP-163||#761329
            THESSALONIKI|LP-164||#7E1E47
            VILNIUS|LP-180||#D5D8EE
            KALMAR|LP-181||#C9A7CB
            MALMO|LP-182||#AD83AF
            GOTEBORG|LP-183||#8B5D8E
            MORA|LP-184||#591861
            FALUN|LP-185||#320939
            STOCKHOLM|LP-186||#EFD1CF
            HELSINKI|LP-187||#ECC0BE
            OULU|LP-188||#D78A8C
            OSLO|LP-189||#AB5265
            COPENHAGEN|LP-190||#5B0E45
            MOSS|LP-191||#6D2C75
            SKAGEN|LP-192||#600D20
            RIGA|LP-193||#663366
            TALLINN|LP-194||#330033
            ODENSE|LP-195||#32174E
            MONACO|LP-199||#93D5F5
            PARIS|LP-200||#CEE6EC
            NANCY|LP-201||#A4CAD9
            STRASBOURG|LP-202||#7CB3CD
            METS|LP-203||#3E8EB7
            LENS|LP-204||#1E74A7
            LILLE|LP-205||#004A7C
            RENNES|LP-206||#003361
            CALAIS|LP-207||#142754
            BREST|LP-208||#0E1A45
            BORDEAUX|LP-209||#69CED6
            NANTES|LP-210||#77A5BF
            GRENOBLES|LP-211||#5188A4
            LYON|LP-212||#004868
            MARSEILLE|LP-213||#C9DBE9
            NIMES|LP-214||#B1C4D4
            MONTPELLIER|LP-215||#7C97B4
            TOULOUSE|LP-216||#4F6D91
            NICE|LP-217||#0E2D52
            AJACCIO|LP-218||#1F2A44
            TAVERNY|LP-219||#4471B2
            GENEVA|LP-220||#005D80
            BASEL|LP-221||#1D327B
            ATHENS|LP-222||#004155
            LIMASSOL|LP-223||#1D2E3F
            PERPIGNAN|LP-224||#001B36
            SAN MARINO|LP-248||#004553
            COMO|LP-249||#A5D6D1
            TORINO|LP-250||#BBDFD8
            MILANO|LP-251||#61BEBC
            BERGAMO|LP-252||#13A9A1
            BRESCIA|LP-253||#007B77
            VENEZIA|LP-254||#005155
            BOLZANO|LP-255||#002E28
            PIACENZA|LP-256||#D2E8D6
            PARMA|LP-257||#9ACB9E
            MODENA|LP-258||#71B26D
            REGGIO EMILIA|LP-259||#438B51
            BOLOGNA|LP-260||#1E5142
            FERRARA|LP-261||#163B2B
            LA SPEZIA|LP-262||#D8DF74
            PISA|LP-263||#C1D678
            PRATO|LP-264||#B6CA70
            LUCCA|LP-265||#86B5A4
            FIRENZE|LP-266||#4E9825
            SIENA|LP-267||#638234
            LIVORNO|LP-268||#224A1E
            PERUGIA|LP-269||#183419
            SASSARI|LP-270||#DCE3D1
            CAGLIARI|LP-271||#BFCDB2
            MESSINA|LP-272||#8E9E75
            CATANIA|LP-273||#2D4823
            PALERMO|LP-274||#29341B
            ROMA|LP-275||#EBE886
            MORIMONDO|LP-276||#E5E14C
            NAPOLI|LP-277||#DAD627
            SALERNO|LP-278||#B9CD28
            FOGGIA|LP-279||#9FA72D
            BARI|LP-280||#725F1D
            CATANZARO|LP-281||#534A19
            RIMINI|LP-282||#002C15
            LECCE|LP-283||#445321
            TIRANA|LP-298||#5A4711
            ISTANBUL|LP-299||#C0B561
            ZAGREB|LP-300||#F4EDB3
            BRATISLAVA|LP-301||#DDD491
            BUCAREST|LP-302||#CBBF5C
            BUDAPEST|LP-303||#AA8413
            PRAGA|LP-304||#917022
            BELGRADE|LP-305||#5C4826
            VIENNA|LP-306||#F6E4C2
            KREMS|LP-307||#DDC69E
            LINZ|LP-308||#D3A96B
            WELS|LP-309||#8A5623
            SALZBURG|LP-310||#6D4B2A
            GRAZ|LP-311||#543B25
            BADEN|LP-312||#2B1307
            BERLIN|LP-313||#F0D0B1
            HAMBURG|LP-314||#EAA77D
            BREMEN|LP-315||#EFA368
            HANNOVER|LP-316||#D56112
            DORTMUND|LP-317||#A55520
            HALLE|LP-318||#613B23
            MUNCHEN|LP-319||#F8E3CC
            STUTTGART|LP-320||#D4B99C
            NURNBERG|LP-321||#AC825D
            MAINZ|LP-322||#7B3F2C
            FRANKFURT|LP-323||#6F4629
            BONN|LP-324||#775135
            KOLN|LP-325||#3B1612
            LEIPZIG|LP-326||#E08741
            INNSBRUCK|LP-327||#B59253
            DUESSELDORF|LP-328||#522A00
            BERN|LP-329||#8C5B34
            ZURICH|LP-330||#C4763F
            LOS ANGELES|LP-340||#ECE9E1
            SAN DIEGO|LP-341||#CCC9C1
            SAN JOSE|LP-342||#BDB9B0
            SAN FRANCISCO|LP-343||#A9A5A0
            OAKLAND|LP-344||#7E7970
            SACRAMENTO|LP-345||#5A5551
            LONG BEACH|LP-346||#444342
            HOUSTON|LP-347||#E5D4C5
            SAN ANTONIO|LP-348||#D1B4A2
            DALLAS|LP-349||#9F7D74
            AUSTIN|LP-350||#5F4444
            EL PASO|LP-351||#403439
            NEW YORK|LP-352||#D7D8D7
            BOSTON|LP-353||#C2C3C9
            CHICAGO|LP-354||#ABAAB4
            PHILLY|LP-355||#5F536D
            WASHINGTON|LP-356||#3A3740
            MIAMI|LP-357||#D8D5C2
            ORLANDO|LP-358||#B8B39E
            TAMPA|LP-359||#9B937B
            JACKSONVILLE|LP-360||#76685C
            KEY WEST|LP-361||#564C42
            FORT MYERS|LP-362||#382E2C
            SEATTLE|LP-363||#D8CCC1
            PORTLAND|LP-364||#B6A18B
            LAS VEGAS|LP-365||#8C7464
            DETROIT|LP-366||#644E41
            BALTIMORE|LP-367||#453536
            INDIANAPOLIS|LP-368||#8A87AC
            MELBOURNE|LP-370||#F8C8B7
            SIDNEY|LP-371||#DEAA9A
            BRISBANE|LP-372||#CF9684
            CHRISTCHURCH|LP-373||#B4857B
            WELLINGTON|LP-374||#8B554C
            MOSCOW|LP-375||#FFA38B
            ST. PETERSBURG|LP-376||#FF8D6D
            KRASONDAR|LP-377||#FF6A39
            DUBAI|LP-378||#89C275
            SAO PAULO|LP-379||#1652A1
            SANTIAGO|LP-380||#EA4890
            TRANSPARENT WHITE|LP-390||#FFFFFF
            TRANSPARENT BLACK|LP-391||#000000
            TRANSPARENT BROWN|LP-392||#43291D
            TRANSPARENT GREEN|LP-393||#FFFFFF
            TRANSPARENT BLUE|LP-394||#020504
            TRANSPARENT RED|LP-395||#FFFFFF
            SILVER|LP-400||#BEC2C5
            GOLD|LP-401||#D5A940
            COPPER|LP-402||#AA6255
            FLUO BLUE|LP-409||#0081C7
            FLUO YELLOW|LP-410||#FFED00
            FLUO ORANGE|LP-411||#F08A00
            FLUO RED|LP-412||#E53517
            FLUO PINK|LP-413||#E30045
            FLUO GREEN|LP-414||#57AB27
            METALIZED BLACK|LP-428||#000000
        """.trimIndent()),
        RawBlock("loop-asphalt-600", "loop-colors:loop-asphalt", """
            BLACK ASPHALT|LP-435||#000000
        """.trimIndent()),
        RawBlock("loop-asphalt-400", "loop-colors:loop-asphalt", """
            ASPHALT|LP-438||#000000
        """.trimIndent()),
        RawBlock("molotow-burner", "molotow-belton:molotow-burner", """
            schwarz||940591|#001117
        """.trimIndent()),
        RawBlock("molotow-coversall", "molotow-belton:molotow-coversall", """
            pure black||348403|#000000
        """.trimIndent()),
        RawBlock("molotow-premium", "molotow-belton:molotow-premium", """
            jasmingelb|#001|327001|#FDF4A6
            zinkgelb|#002|327006|#FEDD3B
            kadmiumgelb|#003|327082|#FFD900
            signalgelb|#004|327165|#FFCC00
            naturweiß|#005|327079|#FAF4E3
            vanille|#006|327115|#FFF0B9
            quitte|#008|327003|#FFD059
            dottergelb|#009|327083|#FBBC00
            melonengelb|#010|327007|#F7AD00
            SLIDER hellorange|#011|327084|#F18D00
            pastellorange|#012|327133|#ED7920
            DARE orange hell|#013|327184|#EB6816
            DARE orange|#014|327085|#E15C0F
            LINDA's sunset|#015|327132|#DF4F1A
            verkehrsrot|#016|327013|#D4021E
            tornadorot|#017|327098|#C2002D
            rubinrot|#018|327166|#990C26
            burgundrot|#019|327086|#71181F
            granat|#020|327185|#4D171C
            GESER schwarzrot|#021|327139|#3E1715
            LOOMIT's aubergine|#022|327046|#3A2119
            pfirsich pastell|#023|327186|#FACDB0
            pfirsich hell|#024|327187|#F8C1A0
            pfirsich|#025|327117|#F6B288
            goldfisch|#026|327008|#F08D4A
            hummer hell|#027|327171|#ED7729
            hummer mittel|#028|327242|#E95F24
            hummer|#029|327010|#E7502A
            blutorange|#030|327135|#BE362A
            schockorange|#031|327088|#DB4430
            MAD C kirschrot|#032|327188|#D80028
            signalrot|#033|327014|#C00417
            aprikose|#034|327116|#F39A5A
            lachsorange|#035|327134|#DB633A
            herbstblatt|#036|327011|#A53513
            LOOMIT's apricot pastell|#037|327189|#F4BEAE
            LOOMIT's apricot hell|#038|327081|#F3A28B
            LOOMIT's apricot mittel|#039|327190|#EE826F
            LOOMIT's apricot|#040|327009|#EB6A4A
            erdbeerrot|#041|327191|#D45646
            pussycat pink|#042|327087|#BE4538
            himbeerrot|#043|327137|#BB2037
            sangria|#044|327106|#9C052D
            grapefruit hell|#045|327192|#F8CAC2
            grapefruit|#046|327122|#F5B2A7
            mauve hell|#047|327193|#E2A09A
            mauve|#048|327109|#CF908C
            altrosa mittel|#049|327194|#A9736A
            altrosa|#050|327129|#996A63
            schweinchenrosa hell|#051|327168|#F7C6CD
            schweinchenrosa|#052|327012|#F0A2B9
            bonbon|#053|327195|#DC7F9F
            lipstick|#054|327196|#B74D74
            purpur|#055|327130|#74324A
            ESHER schmuddelrot|#056|327089|#6C3640
            TILT bubble pink|#057|327197|#DE95BC
            fuchsiapink|#058|327136|#D36AA2
            MAD C psycho pink|#059|327198|#D94476
            telemagenta|#060|327164|#B71D5A
            amarantrot|#061|327099|#910041
            MACrew purple|#062|327153|#68184B
            purpurviolett|#063|327138|#3E1F30
            krokus|#064|327199|#D7C7DB
            lavendel|#065|327200|#BCA0C0
            flieder|#066|327201|#A77EA9
            weintraube|#067|327202|#856195
            brombeere|#068|327203|#673C7C
            johannisbeere|#069|327042|#4C2561
            verrückte pflaume|#070|327044|#251241
            violett dunkel|#071|327043|#33265E
            schwarzviolett|#072|327045|#21194B
            distel|#073|327036|#D9DAD6
            veilchen pastell|#074|327112|#C7C4CF
            veilchen hell|#075|327111|#A3A0C3
            veilchen mittel|#076|327205|#7B7CAB
            veilchen|#077|327110|#6167A2
            veilchen dunkel|#078|327206|#464E96
            night SEEN blue|#079|327041|#243B81
            traube mittel|#080|327039|#505C8E
            traube dunkel|#081|327040|#3A4187
            samtlila|#082|327141|#232A60
            himmelblau hell|#089|327211|#D1E6EE
            himmelblau|#090|327212|#B9DCEC
            schockblau pastell|#091|327163|#A1CEE4
            schockblau hell|#092|327162|#88BCD8
            schockblau mittel|#093|327161|#59A8CD
            schockblau|#094|327032|#0082BA
            tulpenblau hell|#095|327213|#3683BD
            tulpenblau mittel|#096|327214|#0067A3
            tulpenblau|#097|327033|#004A83
            SOTEN lichtblau|#098|327031|#008FB3
            keramik pastell|#099|327029|#77A4C7
            jeansblau|#100|327030|#5088AE
            wild WANE blue|#101|327154|#315484
            marineblau|#102|327209|#1F3D79
            ultramarinblau|#103|327024|#002C5C
            saphirblau|#104|327034|#002E59
            indigo|#105|327210|#002743
            ECB preußischblau dunkel|#106|327105|#00243B
            sturmblau mittel|#106-1|327247|#ACD0DE
            sturmblau|#106-2|327248|#95B4BF
            sturmblau dunkel|#106-3|327249|#7C9BAB
            petrol|#107|327027|#0F3D50
            tiefseeblau|#108|327028|#1B394A
            tiefseeblau dunkel|#109|327104|#00233C
            eisblau dunkel|#110|327019|#97CCD8
            delphinblau|#111|327022|#468F9C
            petroleumblau|#112|327107|#006A7D
            cremeblau|#113|327113|#6BB8C4
            olympiablau|#114|327021|#489AA1
            aqua|#115|327215|#217F8B
            alge|#116|327026|#005362
            babyblau|#117|327016|#B6DCD2
            blue gin|#119|327108|#54A79C
            grünspan|#120|327023|#67B1B8
            karibik|#121|327114|#D0E8DD
            riviera pastell|#122|327216|#A8D5C4
            riviera hell|#123|327072|#80C2AE
            TASTE riviera mittel|#124|327217|#44B39B
            riviera dunkel|#125|327073|#00998A
            lagunenblau|#126|327074|#00857C
            MARTHA marine|#127|327155|#00605B
            türkis dunkel|#128|327156|#00454D
            nori|#129|327218|#003C43
            schwarztürkis|#130|327090|#00333D
            sturmgrün|#131|327053|#AAB98F
            aquamarin|#133|327054|#77A479
            sumpf|#134|327241|#4D7057
            schwarzwaldgrün|#135|327055|#3D5B46
            calypso hell|#137|327068|#C2DEBA
            calypso mittel|#138|327069|#74BD8B
            calypso dunkel|#139|327070|#53A977
            türkisgrün|#140|327219|#00794D
            türkisgrün mittel|#141|327172|#005A3C
            türkisgrün dunkel|#142|327220|#004932
            future green|#143|327145|#004230
            menthol hell|#144|327124|#B8D69D
            menthol|#145|327123|#6BB66C
            universe green|#146|327221|#009952
            salatgrün|#147|327131|#00873F
            kiwi pastell|#148|327120|#DFE38C
            kiwi hell|#149|327119|#BBCE3C
            kiwi|#150|327118|#96B922
            brillantgrün|#152|327061|#B2CC54
            grashüpfer|#153|327064|#88BB3C
            cremegrün|#154|327058|#A6C85C
            hippiegrün|#155|327063|#9EC874
            BACON wasabi|#156|327222|#7FB94F
            cliffgrün|#157|327065|#57AB27
            kleegrün|#158|327223|#2DA43F
            saftgrün|#159|327066|#008834
            mr. green|#160|327096|#00763B
            laubgrün mittel|#160-1|327250|#157727
            laubgrün|#161|327143|#1F5A2E
            MIGHTY green|#162|327062|#94BF3D
            avocado|#163|327224|#6A9619
            farngrün|#164|327142|#567513
            moosgrün|#165|327225|#325815
            chromoxidgrün|#166|327144|#2C4025
            schwarzgrün|#167|327095|#002C1C
            schmetterlingsgrün|#168|327056|#DAE07F
            grüner tee|#169|327226|#BAC579
            P.JAY green|#170|327051|#949955
            amazonas|#171|327052|#908F5E
            camouflage|#172|327227|#5E5D33
            giftgrün|#174|327059|#DEDE2E
            apfel|#175|327128|#CCC545
            hanf|#179|327050|#B4A338
            grüne bohne|#180|327229|#98961E
            birne|#181|327157|#828423
            senf|#182|327049|#D3BA58
            senfgelb|#182-1|327262|#D79A00
            khaki|#183|327078|#AC8C34
            elfenbein hell|#184|327167|#FDEAC5
            sand hell|#184-1|327244|#FAF2DF
            sand mittel|#184-2|327245|#F1DBCB
            sand|#184-3|327246|#D9B092
            quarzsand|#184-4|327254|#D5A78B
            quarzsand mittel|#184-5|327255|#EBCEBE
            quarzsand hell|#184-6|327256|#E9CFC6
            fellweiß|#184-7|327257|#E4D7D0
            milchkaffee|#185|327075|#D5B172
            cappuccino|#186|327235|#A47A4E
            espresso|#187|327094|#86653D
            mocca|#188|327173|#533E27
            saharabeige hell|#189|327230|#F6DEB2
            saharabeige mittel|#190|327231|#F1CB83
            saharabeige|#191|327005|#F0BE6E
            papyrus|#192|327232|#C2964A
            nougat|#193|327077|#B87B3F
            beigebraun|#194|327151|#834E2D
            apricotbeige|#195|327004|#FACF9B
            labrador|#196|327233|#EDBF8B
            kamel|#197|327170|#DC9B55
            ockerbraun|#198|327150|#AC6F2E
            orangebraun hell|#199|327181|#F49E4E
            orangebraun mittel|#200|327182|#D7722E
            orangebraun|#201|327076|#B4591D
            kakao hell|#202|327169|#9F5348
            kakao mittel|#203|327234|#88463D
            kakao|#204|327126|#783A2F
            karamell hell|#204-1|327253|#D7A795
            karamell|#205|327091|#A76745
            walnuss|#206|327183|#75462A
            haselnuss|#207|327092|#5E3121
            schokoladenbraun|#208|327152|#4B301E
            CMP dunkelbraun|#209|327093|#3F271B
            teerschwarz|#210|327159|#3C3B36
            steingrau dunkel|#211|327176|#5D5947
            steingrau mittel|#212|327175|#848169
            steingrau hell|#213|327174|#C4C1AB
            TOAST signalschwarz|#214|327180|#061722
            schwarzgrau neutral|#215|327103|#41403E
            dunkelgrau neutral|#216|327102|#5F5F5C
            CAPARSO mittelgrau neutral|#217|327101|#989892
            hellgrau neutral|#218|327100|#D8D7CC
            mausgrau|#219|327147|#707574
            tiefschwarz|#221|327080|#040608
            schwarzgrau hell|#221-1|327260|#5D5D5B
            schwarzgrau mittel|#221-2|327261|#505050
            schwarzgrau dunkel|#222|327149|#303330
            anthrazitgrau dunkel|#222-1|327258|#2C3134
            anthrazitgrau|#223|327148|#3C4144
            anthrazitgrau mittel|#223-1|327259|#4E5254
            graublau dunkel|#224|327179|#6E7172
            granit|#225|327236|#848788
            graublau mittel|#226|327178|#9C9E9E
            felsengrau|#227|327237|#ADAEAC
            graublau hell|#228|327177|#BDBCBB
            kieselgrau|#229|327238|#CDCBCA
            marmor|#230|327239|#DAD8D8
            signalweiß|#231|327160|#FFFFFF
            neongelb|#232|327350|#FAE500
            neonorange|#233|327351|#FF7300
            neonpink|#234|327352|#FF0073
            neonviolett|#234-1|327356|#971B80
            neonblau|#235|327353|#0073FF
            neontürkis|#235-1|327357|#00A295
            neongrün|#236|327354|#51DA3F
            ANTISTATIK neonrot|#236-1|327355|#FF0000
        """.trimIndent()),
        RawBlock("montana-black", "montana-cans:montana-black", """
            Smash137´s Potato|BLK 1005||#F4E593
            Easter Yellow|BLK 1010||#FFE668
            Kicking Yellow|BLK 1025||#FFDA15
            Yellow|BLK 1030||#FCC000
            Melon Yellow|BLK 1045||#F59E01
            Topaz|BLK 1050||#D37E0A
            Hazle|BLK 1060||#A34C2E
            Pecan Nut|BLK 1070||#6F2F23
            Maroon|BLK 1080||#612316
            Indian Spice|BLK 1110||#E0A600
            Masala|BLK 1120||#B69822
            Delhi|BLK 1130||#A18114
            Bombay|BLK 1140||#6F592A
            Juice|BLK 2060||#F49F24
            Clockwork Orange|BLK 2070||#EF800D
            Pure Orange|BLK 2075||#EA640C
            Halloween|BLK 2085||#E85011
            Code Red|BLK 2093||#E3001B
            Tomorrow|BLK 2110||#F08C48
            Atom´s Megablast|BLK 2120||#EB6A27
            Fire Rose|BLK 3020||#C4091C
            Cardinal|BLK 3062||#6D0827
            Merlot|BLK 3065||#3F2224
            Cherry|BLK 3070||#331028
            Winegum|BLK 3080||#510029
            Miss Piggy|BLK 3100||#F5B8C5
            Pink Cadillac|BLK 3120||#EF8EB0
            Pink Panther|BLK 3130||#E7478A
            Punk Pink|BLK 3145||#C1005E
            Beast|BLK 3148||#E94190
            Freak|BLK 3150||#AA0073
            Purple Rain|BLK 3155||#981569
            Good Times|BLK 3160||#AD0F6C
            Imperator|BLK 3170||#7E154E
            Cocktail|BLK 3200||#F7C0B7
            Mr. Crab|BLK 3220||#F29A84
            Sushi|BLK 3240||#EE8363
            Patpong|BLK 3305||#F3A7B1
            Pink Lemonade|BLK 3310||#EB727B
            Lollipop|BLK 3320||#E74963
            Bloody Mary|BLK 3330||#BA0F3E
            Illusion|BLK 3920||#A8438F
            Magic|BLK 3940||#9D197E
            Bubble Bath|BLK 3995||#C59FC6
            Ms. Jackson|BLK 4000||#B68FBC
            Monster|BLK 4020||#8C4A91
            Pimp Violet|BLK 4040||#6D2C7E
            Galaxy|BLK 4060||#511B57
            Lavender|BLK 4115||#B1A0CA
            Blue Velvet|BLK 4130||#A98DBD
            Royal Purple|BLK 4155||#62579B
            Wizard|BLK 4160||#554189
            Universe|BLK 4182||#0C0940
            Gut|BLK 4210||#AA959C
            Kidney|BLK 4230||#836976
            Liver|BLK 4250||#664B5C
            Dummy|BLK 4260||#DBB4C6
            Plum|BLK 4280||#986D81
            Amethyst|BLK 4290||#5B2C40
            Edelgard|BLK 4310||#CDD2DB
            Brunhilde|BLK 4320||#A2B0CE
            Waltraut|BLK 4330||#6F89BC
            Irmgard|BLK 4340||#4D599A
            Baby Blue|BLK 5020||#6BC8E7
            Light Blue|BLK 5030||#00A2D3
            Horizon|BLK 5070||#0070B8
            Royal Blue|BLK 5077||#054B90
            Ultramarine|BLK 5080||#00326D
            Dark Indigo|BLK 5092||#00173A
            Dove|BLK 5125||#AEC2C0
            Seal|BLK 5140||#52676C
            Space|BLK 5160||#364958
            Trout|BLK 5180||#98B0C6
            Marlin|BLK 5185||#577492
            Whale|BLK 5190||#264B68
            Ice Blue|BLK 5200||#C9E0F2
            Lenor|BLK 5210||#97C4E1
            Blue Lagoon|BLK 5230||#5F97C6
            Knock Out Blue|BLK 5250||#00579E
            Sorrento Blue|BLK 5270||#24327D
            Pistachio|BLK 6000||#E3DE2A
            Acid|BLK 6005||#C9D215
            Slimer|BLK 6010||#A9C707
            Oasis|BLK 6012||#A1A324
            Spring|BLK 6013||#CBD56C
            Wild Lime|BLK 6015||#B5CC22
            Irish Green|BLK 6045||#51AB27
            Boston|BLK 6055||#008132
            Celtic|BLK 6060||#025A27
            Banknote|BLK 6065||#003613
            TAG Green|BLK 6070||#003C1A
            Hippie|BLK 6075||#28C842
            Mescaline|BLK 6080||#29B419
            Woodstock|BLK 6090||#25900C
            Plant|BLK 6095||#00752D
            Tiffany|BLK 6110||#91D1DA
            Cool Cologne|BLK 6130||#4AADC4
            Mermaid|BLK 6150||#0086A1
            Neptune|BLK 6170||#013C4A
            Riffs|BLK 6175||#002A32
            Drops|BLK 6180||#6BDBCF
            Nappies|BLK 6190||#3DC6AC
            Surgery|BLK 6195||#0C8E76
            E2E Green|BLK 6210||#9AC776
            Revolt Green|BLK 6220||#50AE58
            Atlantis|BLK 6240||#007F64
            Olymp|BLK 6310||#C7DBC8
            Hope|BLK 6320||#B0D7BE
            Patina|BLK 6330||#64B699
            Copper Green|BLK 6340||#007764
            Trabi|BLK 6410||#D1D5BC
            Beetle|BLK 6420||#BEC695
            Reseda|BLK 6430||#A3AC7C
            Fog|BLK 6510||#A5B29C
            Mist|BLK 6520||#778B7B
            Storm|BLK 6530||#4C6043
            Bamboo|BLK 6610||#D1C782
            Hemp|BLK 6620||#A3903F
            Boa|BLK 6625||#8F8534
            Pan|BLK 6630||#705A39
            Pear Green|BLK 6710||#BAB526
            Lost Island|BLK 6720||#718428
            Troops|BLK 6725||#565B21
            Toad|BLK 6730||#28401C
            Face|BLK 6905||#D6D1AF
            Hannibal|BLK 6910||#A2A682
            Murdock|BLK 6920||#808460
            B.A Bosko|BLK 6930||#3F3E2A
            Jaws|BLK 7010||#EEF1E6
            Mouse|BLK 7030||#C7C8B8
            Shark|BLK 7050||#999A92
            Rhino|BLK 7070||#5E6460
            Ant|BLK 7080||#48403D
            Gambetta|BLK 7110||#C7BBA8
            Lennox|BLK 7120||#9D9283
            Lambrate|BLK 7130||#7D7268
            Industriilor|BLK 7140||#524038
            Houdini|BLK 7210||#A69FA2
            Morpheus|BLK 7220||#847C82
            Nostradamus|BLK 7230||#57515A
            Ghetto|BLK 7320||#A89E9F
            Dumbo|BLK 7340||#645B5C
            Slate|BLK 7360||#352C2D
            Ivory|BLK 8000||#F2E8C4
            Sand|BLK 8010||#B89247
            Beige|BLK 8020||#D9B980
            Iced Coffee|BLK 8030||#DAAC92
            Cremino|BLK 8040||#CB916C
            Frappé|BLK 8050||#B27A59
            Chocolate|BLK 8060||#7C5035
            Jawa|BLK 8070||#49201A
            Rust|BLK 8080||#902C2E
            Arabian|BLK 8110||#C2A875
            Gobi|BLK 8120||#AB9269
            Syrian|BLK 8130||#90754F
            After|BLK 8210||#9F6B5A
            Snail|BLK 8220||#F5AC8C
            Koi|BLK 8230||#DF5105
            Falling|BLK 8240||#B94709
            Candy Bar|BLK 8250||#5B2607
            Mud|BLK 8260||#512320
            Black|BLK 9001||#030506
            Snow White|BLK 9100||#FFFFFF
            White|BLK 9105||#FBFCF6
            True Yellow|BLK TR 1000||#F9E900
            True Yel. 50%|BLK TR 1010||#FFF562
            True Magenta|BLK TR 4000||#E51175
            True Mag. 50%|BLK TR 4010||#E75D98
            True Cyan|BLK TR 5000||#00B8D2
            True Cyan 50%|BLK TR 5010||#86CEDC
            Copperchrome|Copper||#806031
            Goldchrome|Gold||#826107
            Outline Silver|Outl. Silver||#C0C0C0
            Power Yellow|P1000||#FFDF00
            Power Orange|P2000||#FF5A10
            Power Red|P3000||#E22218
            Power Pink|P4000||#E64690
            Power Violet|P4100||#18225B
            Power Blue|P5000||#00549D
            Power Green|P6000||#67B028
            Silverchrome|Silver||#999999
        """.trimIndent()),
        RawBlock("montana-black-infra", "montana-cans:montana-black", """
            Infra Yellow|IN 1000||#FDFD0B
            Infra Orange|IN 2000||#FD5F00
            Infra Red|IN 3000||#FF0000
            Infra Pink|IN 4000||#EA27C2
            Infra Violet|IN 4500||#CC33FF
            Infra Green|IN 6000||#25F54E
        """.trimIndent()),
        RawBlock("montana-gold-colors", "montana-cans:montana-gold", """
            1000 100% Yellow|||#FFEE00
            2000 100% Cyan|||#00AEC7
            3000 100% Magenta|||#D00065
            Shrimp Pastel|CLASSIC 2100||#F8BDB2
            Shrimp|CLASSIC 2120||#F29C86
            Shrimp Dark|CLASSIC 2130||#EF8464
            Louie Lilac|CLASSIC 4300||#1E2357
            Denim Light|CLASSIC 5200||#C9E1F3
            Denim|CLASSIC 5210||#99C6E3
            Denim Stonewashed|CLASSIC 5220||#6598C6
            Poison Pastel|CLASSIC 6300||#EEE436
            Poison Light|CLASSIC 6310||#E4E028
            Poison|CLASSIC 6320||#C8D215
            Poison Dark|CLASSIC 6330||#ADC70B
            Olive Green|CLASSIC 6340||#494F1F
            Manila Light|CLASSIC 6400||#A7A97A
            Manila Green|CLASSIC 6410||#838663
            Manila Dark|CLASSIC 6420||#46412C
            Sand|CLASSIC 8300||#B89247
            Hazelnut|CLASSIC 8310||#80441E
            Chestnut|CLASSIC 8320||#4E1A1B
            Vanilla|G1000||#FFEE9B
            Easter Yellow|G1010||#FFE363
            Citrus|G1020||#FFD900
            Banana|G1030||#EABF00
            Asia|G1040||#E5BF00
            Curry|G1050||#C6A018
            Mustard|G1060||#A98715
            Everglade|G1080||#7E6430
            Butta|G1100||#FDF07A
            Brimstone|G1110||#F4E600
            Banana Joe|G1120||#DDCF1E
            Pepperoni Mild|G1130||#BBB62F
            Pepperoni Hot|G1140||#8B812F
            Reed|G1150||#625E25
            Nato|G1170||#46432B
            Military Green|G1180||#252A22
            Pudding|G1200||#FFDD70
            Yellow Submarine|G1210||#FECC33
            Yellow Cab|G1220||#FBB800
            Yolk|G1230||#F6A000
            Golden Yellow|G1240||#EB8904
            Terra|G1250||#C87620
            Mushroom|G1260||#523B1C
            Bone|G1400||#F7EAD9
            Latte|G1410||#F6E2C9
            Cappucino|G1420||#ECC6A8
            Make-Up|G1430||#DAAC92
            Toffee|G1440||#CD926E
            Hot Chocolate|G1450||#885845
            Palish Brown|G1470||#6E4E34
            White Orange|G2000||#FBE9CF
            Orange Ice|G2010||#FEE9D9
            Creme Orange|G2020||#F9C173
            Blast Orange|G2030||#F4A34A
            Scampi|G2040||#F29530
            Orangina|G2050||#F08217
            Capri|G2060||#EE7412
            Orange|G2070||#EC6415
            Pure Orange|G2080||#EA5818
            Red Orange|G2090||#E43E1D
            Blood Orange|G2095||#DC0824
            Lychee|G3000||#F7BFC1
            Bazooka Joe|G3010||#ED8798
            Strawberry|G3020||#E73C4E
            Raspberry|G3030||#D6053E
            Ketchup|G3040||#BA1829
            Brick|G3050||#971C24
            Royal Red|G3060||#721E23
            Purple Red|G3070||#5B181C
            Black Red|G3080||#3E1511
            Vampirella|G3085||#271619
            Frozen Strawberry|G3100||#F9D2DB
            Frozen Raspberry|G3110||#EFA9C2
            Pink Pink|G3130||#D84389
            Cherry Blossom|G3150||#8E135F
            Pale Pink|G4000||#E1C3CC
            Mortadella|G4010||#D1A3AD
            Dusty Pink|G4020||#99536A
            Ancient Pink|G4030||#824150
            Powder Pink|G4040||#792B3E
            White Lilac|G4100||#D2C1DD
            Light Lilac|G4110||#A999C6
            Teen Spirit|G4130||#7C6EAC
            Lavender|G4150||#55428A
            Gonzo|G4160||#39377E
            Blue Velvet|G4170||#2C3068
            Welsh|G4180||#1D1938
            Cassis|G4190||#10182A
            Crocus|G4200||#CDB7D5
            Viola|G4210||#B08EBD
            Sweet Dream|G4220||#8E4D91
            Valerie|G4230||#6F317F
            Lakers|G4240||#522158
            Deep Purple|G4250||#5C3154
            Black Purple|G4260||#321440
            Flipper|G5000||#CCE8F0
            Fresh Blue|G5010||#A3D7E8
            Baby Blue|G5020||#6FC8E6
            Bermuda|G5030||#00AFD8
            Light Blue|G5040||#00A1D1
            Sky Blue|G5050||#008CC7
            Blue Magic|G5060||#006EAD
            Signal Blue|G5075||#005089
            Ultramarine|G5080||#003A6F
            Blue Note|G5085||#003457
            Nautilus|G5090||#0C2337
            Polar Blue|G5100||#D8EDED
            Summit|G5105||#B9E0EA
            Himalaya|G5110||#8ACADC
            Mt. Everest|G5120||#60A1B8
            Mt. Fuji|G5140||#477283
            Fjord|G5150||#255162
            Deep Sea|G5160||#0B353F
            Navy|G5170||#062331
            Venom|G6000||#E5EECE
            Linden Green|G6010||#C5DDA8
            Green Apple|G6020||#A3C96D
            Lime|G6030||#ADC70B
            Lawn Green|G6040||#7EB125
            Greenery|G6050||#008332
            Fern Green|G6060||#006030
            Smaragd Green|G6070||#005129
            Jungle Green|G6080||#003B24
            Deep Forest|G6090||#00301F
            Liberty|G6100||#EEF5E3
            Malachite Light|G6120||#AFD8C1
            Malachite|G6130||#65B79A
            Malachite Dark|G6150||#3A8469
            Pine|G6160||#006D58
            Venice|G6200||#E5F1E6
            Can2 Cool Candy|G6210||#C1E2E0
            Pool|G6230||#93D1D9
            Dolphins|G6250||#50ADC5
            Aqua|G6260||#0086A2
            Reef|G6270||#006275
            Petrol|G6280||#00363F
            Pebble|G7000||#F1EFEA
            Marble|G7010||#E1E2E2
            Wall|G7020||#C6C7C6
            Iron Curtain|G7030||#ACAAA3
            Roof|G7050||#7C7E7C
            Gravel|G7060||#626969
            Stealth|G7070||#313C3F
            Coke|G7090||#0E1514
            Dolomite|G7210||#F2EEE7
            Ceramic|G7220||#E8E4DB
            Buzzard|G7230||#D5D3CA
            Yosemite|G7240||#DAD7C9
            Asphalt|G7250||#A09F9A
            Meteorite|G7260||#76726B
            Basalt|G7270||#55524D
            Elm|G8000||#F7F0CE
            Sahara Yellow|G8010||#E5D49C
            Sahara Beige|G8020||#DABA7F
            Duck Season|G8040||#B29260
            Salmon|G8070||#F3A68C
            Dirty Apricot|G8080||#D78366
            Aubergine|G8085||#351E1F
            Nougat|G8090||#B77452
            Orange Brown|G8100||#7D3924
            Rusto Coat|G8110||#912B2F
            Wine Red|G8115||#3E161B
            Cacao|G8120||#54311F
            Anthracite|G8145||#192120
            Concrete|G8150||#353028
            Lip|G8170||#934D54
            Paris|G8175||#CBB5BF
            Brain|G8180||#D6C4BF
            Flesh|G8190||#D5BFB9
            Yellow Light|SHOCK 1000||#FFDE09
            Yellow|SHOCK 1010||#FCBC00
            Orange Light|SHOCK 2000||#EF7D0A
            Orange|SHOCK 2010||#EA5B18
            Orange Dark|SHOCK 2020||#E6301D
            Red|SHOCK 3000||#CB0D1F
            Kent Blood Red|SHOCK 3020||#AF151A
            Pink Light|SHOCK 4000||#E888B2
            Pink|SHOCK 4010||#C73475
            Lilac|SHOCK 4220||#312C66
            Blue Light|SHOCK 5000||#7FC5D3
            Blue|SHOCK 5010||#004D91
            Blue Dark|SHOCK 5020||#05356C
            Green Light|SHOCK 6000||#7EB627
            Green|SHOCK 6010||#007A37
            Green Dark|SHOCK 6020||#00612F
            Brown Light|SHOCK 8000||#B1592A
            Brown|SHOCK 8010||#5A3121
            Brown Dark|SHOCK 8020||#312111
            Black|SHOCK 9000||#0C0C0A
            White|SHOCK 9100||#FFFFFF
            White Cream|SHOCK 9110||#F8F5E9
            White Pure|SHOCK 9120||#FFFFFF
        """.trimIndent()),
        RawBlock("montana-gold-fluorescent", "montana-cans:montana-gold", """
            Flash Yellow|F1000||#F7FF73
            Power Orange|F2000||#FF7545
            Fire Red|F3000||#FE0001
            Gleaming Pink|F4000||#FF00FF
            Flame Blue|F5000||#00AFFF
            Acid Green|F6000||#4EF684
            Active Cyan|F6200||#00FEF5
            Disco White|F9100||#F7FCFF
        """.trimIndent()),
        RawBlock("montana-gold-chrome", "montana-cans:montana-gold", """
            Silverchrome|M 1000||#BCC6CC
            Copperchrome|M 2000||#996633
            Goldchrome|M 3000||#AF9A6A
        """.trimIndent()),
        RawBlock("montana-gold-metallic", "montana-cans:montana-gold", """
            Silver Matt|METALLIC 1100||#9B9B9B
            Gold Matt|METALLIC 3010||#806E44
        """.trimIndent()),
        RawBlock("montana-gold-transparent", "montana-cans:montana-gold", """
            Transparent Yellow Cab|T1220||#FFD571
            Transparent Ketchup|T3040||#B80D25
            Transparent Cherry Blossom|T3150||#8C0B5E
            Transparent Ultramarine|T5080||#2569B1
            Transparent Olive Green|T6340||#6C753F
            Transparent Gravel|T7060||#8C9393
            Transparent Hazelnut|T8310||#905C3B
            Transparent Black|T9000||#030201
            Transparent White|T9100||#E7E2E2
        """.trimIndent()),
        RawBlock("montana-ultra-wide", "montana-cans:montana-ultra-wide", """
            Black|||#000000
            Blue|||#004C91
            Halloween|||#E85011
            Kicking Yellow|||#FFDA15
            Light Blue|||#00A2D3
            Nappies|||#3DC6AC
            Power Green|||#68B028
            Red|||#CB031C
            Royal Purple|||#62579B
            Shark|||#999A92
            Silverchrome|||#8D8D8D
            Snow White|||#FFFFFF
        """.trimIndent()),
        RawBlock("mtn-94", "mtn-montana-colors:mtn-94", """
            Air White Transparent||EX0149310|#F7F7F7
            Atmosphere Blue Transparent||EX0140330|#AFCCDF
            Aura Violet Transparent||EX0140303|#C5ADD0
            Breeze Green Transparent||EX0146318|#A1D5CF
            Ethereal Yellow Transparent||EX0141321|#E1DB8E
            Fluorescent Fucsia||EX0140603M|#EE4D9B
            Fluorescent Violet||EX0140607M|#9857A5
            Frame Gold||EX0140127|#C0B068
            Haze Orange Transparent||EX0142304|#FBB36D
            Jewel Silver||EX0140126|#B0B0B0
            Judea Brown Transparent||EX0148317|#D2B598
            Shadow Black Transparent||EX0149311|#8F8F8F
            Shadow Grey Transparent||EX0149312|#A6A6A7
            Soul Red Transparent||EX0143320|#EDA795
            Triumph Copper||EX0140128|#B87333
            Fluorescent Blue|MTN 94|EX0140605M|#008DD2
            Fluorescent Green|MTN 94|EX0140604M|#61BB46
            Fluorescent Orange|MTN 94|EX0140601M|#F68B1F
            Fluorescent Red|MTN 94|EX0140602M|#EF3A4D
            Fluorescent Yellow|MTN 94|EX0140600M|#FDEF4C
            Coffee Brown|RV-100|EX0140100M|#402009
            Ebony Brown|RV-101|EX0140101M|#2F1109
            Bone White|RV-1013|EX0141013M|#F3EFD6
            Lemon Yellow|RV-1016|EX0141016M|#DCD872
            Peach|RV-1017|EX0141017M|#E6A65D
            Dalai Orange|RV-102|EX0140102M|#FDDCA3
            Light Yellow|RV-1021|EX0141021M|#FEDF00
            Medium Yellow|RV-1028|EX0141028M|#FFA300
            Plural Orange|RV-103|EX0140103M|#FAC67E
            Tangerine|RV-105|EX0140105M|#F5A54A
            Lava Orange|RV-106|EX0140106M|#EF8407
            Mars Orange|RV-107|EX0140107M|#E64715
            Phoenix Orange|RV-108|EX0140108M|#BE3819
            Canarias Yellow|RV-109|EX0140109M|#FFF058
            Yosemite Yellow|RV-110|EX0140110M|#C7B300
            Babel Green|RV-111|EX0140111M|#A29400
            Mission Green|RV-112|EX0140112M|#766A10
            Dragon Green|RV-113|EX0140113M|#5E5003
            Maya Green|RV-114|EX0140114M|#3D3408
            Tutti Frutti|RV-115|EX0140115M|#EA949D
            Blood Red|RV-116|EX0140116M|#D52F25
            Rita Grey|RV-118|EX0140118M|#CDD0D1
            London Grey|RV-119|EX0140119M|#898B8E
            Wolf Grey|RV-120|EX0140120M|#5B5B5E
            Icarus Grey|RV-121|EX0140121M|#48484B
            Frisco Green|RV-124|EX0140124M|#D4E19E
            Neon Green|RV-125|EX0140125M|#A5B700
            Toscana Green|RV-126|EX0140126M|#2B491E
            Era Green|RV-127|EX0140127M|#142F0F
            Oregano Green|RV-129|EX0140129M|#AFAB00
            Euskadi Green|RV-130|EX0140130M|#50590D
            Comarca Green|RV-131|EX0140131M|#333B08
            Borneo Green|RV-132|EX0140132M|#283307
            Dharma Green|RV-133|EX0140133M|#1E2705
            Infinity Green|RV-134|EX0140134M|#131C04
            Safari Brown|RV-135|EX0140135M|#EADFA8
            Inca Brown|RV-136|EX0140136M|#D9B365
            Kraft Brown|RV-137|EX0140137M|#BD9B61
            Marrakech|RV-138|EX0140138M|#99743F
            Sequoia Brown|RV-139|EX0140139M|#6F5229
            Mole Brown|RV-140|EX0140140M|#503915
            Gondola Brown|RV-141|EX0140141M|#412C13
            Gemini Green|RV-142|EX0140142M|#E1F0E8
            Bali Green|RV-144|EX0140144M|#7BC6C0
            Erasmus Green|RV-145|EX0140145M|#5BB5B5
            Glory Blue|RV-146|EX0140146M|#2D6A75
            Pegasus Blue|RV-147|EX0140147M|#003640
            Hercules Blue|RV-148|EX0140148M|#002628
            Hydra Blue|RV-149|EX0140149M|#8ECAE5
            Argo Blue|RV-150|EX0140150M|#44B3DF
            Freedom Blue|RV-151|EX0140151M|#0098D2
            Europe Blue|RV-152|EX0140152M|#0074B0
            Twister Blue|RV-154|EX0140154M|#042151
            Barceloneta Blue|RV-156|EX0140156M|#CAE4F0
            Thalassa Blue|RV-157|EX0140157M|#A2D3EA
            Perseus Blue|RV-158|EX0140158M|#7FB8D5
            Odyssey Blue|RV-159|EX0140159M|#6EA4BE
            Pistachio Green|RV-16|EX0140016M|#BDD268
            Eureka Blue|RV-160|EX0140160M|#467289
            Jase Blue|RV-161|EX0140161M|#2E4A5B
            Deep Blue|RV-162|EX0140162M|#003447
            Poseydon Blue|RV-163|EX0140163M|#00202C
            Tokyo Pink|RV-164|EX0140164M|#F7C7D7
            Orchid Pink|RV-165|EX0140165M|#EC7FAA
            Açai Red|RV-166|EX0140166M|#9A004B
            Rioja Red|RV-167|EX0140167M|#6B0037
            Anger Red|RV-168|EX0140168M|#550026
            Taurus Red|RV-169|EX0140169M|#36001C
            Persia Violet|RV-170|EX0140170M|#C4A7D2
            Community Violet|RV-171|EX0140171M|#9D8ABC
            Destiny Violet|RV-172|EX0140172M|#8270A3
            Ultraviolet|RV-173|EX0140173M|#6B4D8D
            Venus Violet|RV-174|EX0140174M|#483366
            Electra Violet|RV-175|EX0140175M|#32234E
            Sensible Brown|RV-176|EX0140176M|#EFD9D0
            Eldorado|RV-177|EX0140177M|#F1C700
            Tibet|RV-178|EX0140178M|#D58B26
            Bonsai Green|RV-179|EX0140179M|#B8BB86
            Thai Green|RV-180|EX0140180M|#8E966E
            Labyrinth Green|RV-181|EX0140181M|#47492B
            Emerald Green|RV-182|EX0140182M|#009E8F
            Beryl Green|RV-183|EX0140183M|#117774
            Rain Blue|RV-184|EX0140184M|#C4E7F8
            Angel Blue|RV-185|EX0140185M|#EAF0F5
            Virgin Green|RV-186|EX0140186M|#F5FAF7
            Vespa Green|RV-187|EX0140187M|#F1F5DF
            Shining Green|RV-188|EX0140188M|#F2EDBE
            Ipanema Yellow|RV-189|EX0140189M|#FFF9C3
            Malta White|RV-190|EX0140190M|#F9F6E9
            Jaima Brown|RV-191|EX0140191M|#F1E8DE
            Sundance|RV-192|EX0140192M|#FFEBC2
            Chewing Gum|RV-193|EX0140193M|#F6C3D3
            Supernova Pink|RV-194|EX0140194M|#FCE6EB
            Shiva Violet|RV-195|EX0140195M|#E5CCE1
            Saudade Pink|RV-196|EX0140196M|#F2DDDD
            Penelope Brown|RV-197|EX0140197M|#F8EDE7
            Stardust Grey|RV-198|EX0140198M|#EEF0F1
            Java Green|RV-199|EX0140199M|#86C8B4
            Party Yellow|RV-20|EX0140020M|#FFEF8C
            Plancton|RV-200|EX0140200M|#E8D6C8
            Orange|RV-2004|EX0142004M|#EA640D
            Scarlet Brown|RV-201|EX0140201M|#8E6061
            Mosquito Brown|RV-202|EX0140202M|#684445
            Oak Brown|RV-203|EX0140203M|#A86059
            Interrail Brown|RV-204|EX0140204M|#9F3D44
            Warrior Brown|RV-205|EX0140205M|#5A1521
            Mango|RV-207|EX0140207M|#E87722
            Madrid Red|RV-241|EX0140241M|#F65058
            Babylon Blue|RV-243|EX0140243M|#3D5588
            Cyan|RV-245|EX0140245M|#00FFFF
            Sonar Green|RV-265|EX0140265M|#A0BE56
            Psycho Green|RV-266|EX0140266M|#D5E739
            Sulfur Yellow|RV-267|EX0140267M|#FAEB37
            Tramontana Blue|RV-268|EX0140268M|#007788
            Genesis Blue|RV-269|EX0140269M|#179DAB
            Vampire Violet|RV-27|EX0140027M|#140632
            Formentera Blue|RV-270|EX0140270M|#00B4BC
            Mystic Green|RV-271|EX0140271M|#25BD59
            Mint Green|RV-272|EX0140272M|#29CB7E
            Iguana Green|RV-273|EX0140273M|#8CC947
            Reverend Violet|RV-274|EX0140274M|#623371
            Raval Violet|RV-275|EX0140275M|#94679C
            Bishop Violet|RV-276|EX0140276M|#A572B1
            Disco Pink|RV-277|EX0140277M|#BD51A2
            Joker Pink|RV-278|EX0140278M|#E44C9A
            Rosario Pink|RV-279|EX0140279M|#DC4588
            Cosmos Violet|RV-28|EX0140028M|#241C46
            Hulk Green|RV-280|EX0140280M|#41A248
            Laser Green|RV-281|EX0140281M|#99C221
            Laos Green|RV-282|EX0140282M|#8FCB24
            Sultan Violet|RV-283|EX0140283M|#764077
            Electric Blue|RV-30|EX0140030M|#005891
            Tofu Grey|RV-300|EX0140300M|#FEF9E3
            Vivid Red|RV-3001|EX0143001M|#B3061E
            Bordeaux Red|RV-3004|EX0143004M|#610819
            Cherokee Red|RV-3007|EX0143007M|#3A0807
            Placebo Grey|RV-301|EX0140301M|#F5EFD6
            Fever Red|RV-3017|EX0143017M|#DC534D
            Koala Grey|RV-302|EX0140302M|#D8CDC3
            Light Red|RV-3020|EX0143020M|#EF3A38
            Native Grey|RV-303|EX0140303M|#BCB2AD
            Balboa Grey|RV-304|EX0140304M|#A29690
            Cloud Grey|RV-305|EX0140305M|#C9D2D7
            Winter Grey|RV-306|EX0140306M|#B7C1CD
            Jaws Grey|RV-307|EX0140307M|#ABB5C1
            Whale Grey|RV-308|EX0140308M|#6B7C91
            Chernobyl Grey|RV-309|EX0140309M|#5E7386
            Republic Violet|RV-310|EX0140310M|#DACBE5
            Woodstock Violet|RV-311|EX0140311M|#CDC3E1
            Sagan Blue|RV-312|EX0140312M|#C1CAE8
            Martinez Blue|RV-313|EX0140313M|#AEBEE3
            Rosemary Blue|RV-314|EX0140314M|#9DB1DC
            Dancer Blue|RV-315|EX0140315M|#85A0D3
            Marseille Blue|RV-316|EX0140316M|#6386C3
            Porto Blue|RV-317|EX0140317M|#616CB1
            Ween|RV-318|EX0140318M|#3B54A1
            Tuareg Blue|RV-319|EX0140319M|#263284
            Mantra Blue|RV-320|EX0140320M|#302B66
            April Violet|RV-321|EX0140321M|#F0E0ED
            Arlet Violet|RV-322|EX0140322M|#D6BBD8
            Mandala Violet|RV-323|EX0140323M|#BC90C1
            Guacamole Green|RV-34|EX0140034M|#81A512
            Chocolate Brown|RV-35|EX0140035M|#41302A
            Erika|RV-4003|EX0144003M|#E85B99
            Magenta|RV-4010|EX0144010M|#D90075
            Clandestine Red|RV-47|EX0140047M|#950825
            Solar Orange|RV-50|EX0140050M|#F7B060
            Dark Blue|RV-5005|EX0145005M|#003875
            Navy Blue|RV-5013|EX0145013M|#010E30
            Turquoise|RV-5018|EX0145018M|#008691
            Krypton Green|RV-60|EX0140060M|#83890E
            Amazonas Green|RV-6009|EX0146009M|#0F2405
            Valley Green|RV-6018|EX0146018M|#4A7518
            Luminous  Green|RV-6027|EX0146027M|#A1D5CF
            Respect Pink|RV-64|EX0140064M|#B59892
            Anthracite Grey|RV-7016|EX0147016M|#363538
            Pearl Grey|RV-7040|EX0147040M|#B5B8BA
            Siberian Grey|RV-7047|EX0147047M|#DBDDDF
            Night Red|RV-77|EX0140077M|#2D0604
            Metropolis Grey|RV-78|EX0140078M|#262227
            Mustard|RV-8023|EX0148023M|#A76225
            Boreal Pink|RV-86|EX0140086M|#E3BFC3
            Stereo Pink|RV-87|EX0140087M|#CA95A4
            Single Pink|RV-88|EX0140088M|#A06C7E
            Compact Red|RV-89|EX0140089M|#864A54
            Bitacora Red|RV-90|EX0140090M|#582B3A
            White|RV-9010|EX0149010M|#FFFFFF
            Black|RV-9011|EX0149011M|#000000
            Pandora Red|RV-91|EX0140091M|#4F1F30
            Gaudi Red|RV-92|EX0140092M|#321129
            Stendhal Red|RV-93|EX0140093M|#1E000E
            Dingo Brown|RV-94|EX0140094M|#E8D0B7
            Tana Brown|RV-95|EX0140095M|#D2A785
            Montserrat|RV-96|EX0140096M|#CC955E
            Chiapas Brown|RV-97|EX0140097M|#A0682B
            Bean Brown|RV-98|EX0140098M|#A65F2F
            Glace Brown|RV-99|EX0140099M|#7A3D24
        """.trimIndent()),
        RawBlock("mtn-hardcore", "mtn-montana-colors:mtn-hardcore", """
            Black Matt||EX014H0901|#000000
            Black Satin||EX014H0903|#000000
            Chrome Silver||EX014H0101|#DBE4EB
            Copper||EX014H0103|#723E1E
            Gold||EX014H0102|#D4AF37
            White Matt||EX014H0902|#FFFFFF
            White Satin||EX014H0906|#FFFFFF
            Alice Pink|RV- 348|EX014H0348|#F4ADC5
            Caribbean Blue|RV- 5021|EX014H5021|#007F80
            Bone White|RV-1013|EX014H1013|#F3EFD6
            Peach|RV-1017|EX014H1017|#F9BA57
            Light Yellow|RV-1021|EX014H1021|#FFE100
            Medium Yellow|RV-1028|EX014H1028|#F6A800
            Ganges Yellow|RV-11|EX014H0011|#D49E16
            Himalayan Blue|RV-13|EX014H0013|#96D7E9
            Planet Blue|RV-14|EX014H0014|#008098
            Apple Green|RV-15|EX014H0015|#ACB681
            Pistachio Green|RV-16|EX014H0016|#B0C643
            Rust Red|RV-18|EX014H0018|#6D2601
            Party Yellow|RV-20|EX014H0020|#FFF048
            Pastel Orange|RV-2003|EX014H2003|#EC753B
            Orange|RV-2004|EX014H2004|#E95E0F
            Atacama Yellow|RV-206|EX014H0206|#FBCB8C
            Mango|RV-207|EX014H0207|#E77A19
            Pumpkin|RV-208|EX014H0208|#F6AD6B
            Calcutta Orange|RV-209|EX014H0209|#DC4126
            Surgical Green|RV-21|EX014H0021|#009473
            Prometheus Orange|RV-210|EX014H0210|#910E14
            Love Pink|RV-211|EX014H0211|#EE87AD
            Akari Red|RV-212|EX014H0212|#C50041
            Merlot Red|RV-213|EX014H0213|#762A3D
            Violet|RV-214|EX014H0214|#9993C3
            Prophet Violet|RV-215|EX014H0215|#6D63A5
            Anonymous Violet|RV-216|EX014H0216|#45347A
            Avatar Blue|RV-217|EX014H0217|#00A2DD
            Neptune Blue|RV-218|EX014H0218|#004578
            Paris Green|RV-219|EX014H0219|#8BC8AA
            UFO Green|RV-220|EX014H0220|#5BB89E
            Persephone Green|RV-221|EX014H0221|#005231
            Beach Yellow|RV-222|EX014H0222|#FFF386
            Witch Violet|RV-224|EX014H0224|#C8739F
            Geisha Violet|RV-225|EX014H0225|#C15C92
            Tube Violet|RV-226|EX014H0226|#7C3F60
            Waimea Blue|RV-227|EX014H0227|#6F9FD0
            Zeppelin Blue|RV-228|EX014H0228|#4875B3
            Andromeda Blue|RV-229|EX014H0229|#465499
            Leviathan Blue|RV-230|EX014H0230|#0D0F49
            Cousteau Blue|RV-231|EX014H0231|#1BB2C4
            Glacier Blue|RV-232|EX014H0232|#009CAB
            Christiania Blue|RV-233|EX014H0233|#006675
            Indigo Blue|RV-234|EX014H0234|#004750
            Poison Green|RV-235|EX014H0235|#DEDD3A
            Mojito Green|RV-236|EX014H0236|#CED50A
            Cologno N. Green|RV-237|EX014H0237|#3E8515
            Luxor Yellow|RV-239|EX014H0239|#FFBF0F
            Golden Green|RV-24|EX014H0024|#A7CD9A
            Madrid Red|RV-241|EX014H0241|#E5352D
            Soviet Red|RV-242|EX014H0242|#8D0000
            Babylon Blue|RV-243|EX014H0243|#374D8B
            Druide Brown|RV-246|EX014H0246|#EECF99
            Tepuy Brown|RV-247|EX014H0247|#DEB276
            Baobab Brown|RV-248|EX014H0248|#CC9456
            Greyhound Brown|RV-249|EX014H0249|#B0763F
            Rambo Green|RV-250|EX014H0250|#8F995B
            Forest Green|RV-251|EX014H0251|#46502C
            Unicorn Yellow|RV-252|EX014H0252|#FFFFBF
            Element Green|RV-253|EX014H0253|#C5CC8F
            Max Green|RV-254|EX014H0254|#9FE5C2
            Patagonia Blue|RV-255|EX014H0255|#83CCDF
            Malva|RV-256|EX014H0256|#ACA6D1
            Princess Violet|RV-257|EX014H0257|#CA87B6
            Manga Pink|RV-258|EX014H0258|#FFA2CA
            Flamingo|RV-259|EX014H0259|#FF958E
            Iroko Red|RV-260|EX014H0260|#5E0000
            Pangea Brown|RV-261|EX014H0261|#933B00
            Matter Grey|RV-262|EX014H0262|#B0B0B0
            Sputnik Grey|RV-263|EX014H0263|#575757
            Galaxy Violet|RV-264|EX014H0264|#2F2280
            Vampire Violet|RV-27|EX014H0027|#2A1E48
            Mint Green|RV-272|EX014H0272|#60B565
            Arctic Blue|RV-29|EX014H0029|#6BDCFF
            Blue Violet|RV-3|EX014H0003|#574A96
            Electric Blue|RV-30|EX014H0030|#007FC4
            Vivid Red|RV-3001|EX014H3001|#C90019
            Bordeaux Red|RV-3004|EX014H3004|#82131D
            Light Red|RV-3020|EX014H3020|#E5352D
            Lewis Blue|RV-32|EX014H0032|#213A8F
            Colorado Red|RV-33|EX014H0033|#E74F45
            Guacamole Green|RV-34|EX014H0034|#76B14F
            Treze Violet|RV-349|EX014H0349|#F6B8D0
            Chocolate Brown|RV-35|EX014H0035|#4D2200
            Pure Purple|RV-350|EX014H0350|#8F154B
            Hortensia Blue|RV-351|EX014H0351|#889ED1
            Gala Blue|RV-352|EX014H0352|#5D78BA
            Julione Blue|RV-353|EX014H0353|#40549F
            Universe Blue|RV-354|EX014H0354|#0F2354
            Fukushima Blue|RV-355|EX014H0355|#8ECFD3
            Vintage Blue|RV-356|EX014H0356|#97D2D0
            Iceberg Blue|RV-357|EX014H0357|#6EC3BF
            Nenufar Blue|RV-358|EX014H0358|#60B3AC
            Mururoa Blue|RV-359|EX014H0359|#008C8D
            Major Blue|RV-360|EX014H0360|#1F6363
            Potosi Green|RV-361|EX014H0361|#B3DFD2
            Mantis Green|RV-362|EX014H0362|#78BE7A
            Natura Green|RV-363|EX014H0363|#00964F
            Reggae Green|RV-364|EX014H0364|#006942
            Puchineli White|RV-365|EX014H0365|#F6F7DE
            Squatter Grey|RV-366|EX014H0366|#C4C5C6
            Ripley Grey|RV-39|EX014H0039|#7E7F82
            Light Green|RV-4|EX014H0004|#90C983
            Nazgul Grey|RV-40|EX014H0040|#928782
            Erika|RV-4003|EX014H4003|#DE336B
            Cherry|RV-4007|EX014H4007|#582741
            Magenta|RV-4010|EX014H4010|#DD1D5A
            Regina Grey|RV-42|EX014H0042|#B7A794
            Lutecia Green|RV-5|EX014H0005|#005900
            Ultramarine Blue|RV-5002|EX014H5002|#102775
            Dark Blue|RV-5005|EX014H5005|#00659D
            Ocean Blue|RV-5020|EX014H5020|#00454E
            Arkalis Grey|RV-55|EX014H0055|#EBE6D6
            City Grey|RV-57|EX014H0057|#CABDB0
            Light Grey|RV-6|EX014H0006|#E6E6E6
            Olive Green|RV-6003|EX014H6003|#60683D
            Amazonas Green|RV-6009|EX014H6009|#0F2405
            Khaki Green|RV-6013|EX014H6013|#727E48
            Dark Green|RV-6016|EX014H6016|#0A8564
            Valley Green|RV-6018|EX014H6018|#589720
            Pale Green|RV-6019|EX014H6019|#CCE0AC
            Cream|RV-7|EX014H0007|#FED792
            Anthracite Grey|RV-7016|EX014H7016|#464648
            Dark Grey|RV-7031|EX014H7031|#616264
            Pearl Grey|RV-7040|EX014H7040|#7B7C7E
            Aurora Blue|RV-73|EX014H0073|#C8D3ED
            Costa Brava Blue|RV-74|EX014H0074|#94BFE5
            Nostromo Blue|RV-75|EX014H0075|#020E37
            Light Blue|RV-8|EX014H0008|#2ABEEF
            Toasted Brown|RV-8002|EX014H8002|#8A5531
            Tobacco Brown|RV-8017|EX014H8017|#513314
            Mustard|RV-8023|EX014H8023|#B9501A
            Apricot|RV-9|EX014H0009|#FAC294
            Divinity White|RV-9010|EX014H9010|#FFFFFF
            Black|RV-9011|EX014H9011|#000000
        """.trimIndent()),
        RawBlock("mtn-mega", "mtn-montana-colors:mtn-mega", """
            White|R-9010|EX0169010|#FFFFFF
            Black|R-9011|EX0169011|#000000
            Light Yellow|RV-1021|EX0161021|#FFE100
            Pastel Orange|RV-2003|EX0162003|#EC753B
            Surgical Green|RV-21|EX0160021|#63E6BE
            Violett|RV-214|EX0160214|#A4A0D0
            Anonymous Violet|RV-216|EX0160216|#45347A
            Paris Green|RV-219|EX0160219|#8BC8AA
            Geisha Violet|RV-225|EX0160225|#C15C92
            Electric Blue|RV-30|EX0160030|#007FC4
            Bordeaux Red|RV-3004|EX0163004|#8B2C3D
            Light Red|RV-3020|EX0163020|#E5352D
            Lutecia Green|RV-5|EX0160005|#005900
            Dark Blue|RV-5005|EX0165005|#1357BE
            Pearl Grey|RV-7040|EX0167040|#7B7C7E
            Toasted Brown|RV-8002|EX0168002|#8A5531
        """.trimIndent()),
        RawBlock("mtn-vice", "mtn-montana-colors:mtn-vice", """
            Alive Orange||EX014VI0005|#F6B693
            Atmos Violet||EX014VI0024|#00235B
            Bhutan Orange||EX014VI0008|#D16105
            Black Mamba||EX014VI9011|#000000
            Bougainville Pink||EX014VI0015|#F13778
            Bunker Grey||EX014VI0048|#3D4043
            Butterfly Grey||EX014VI0047|#807F84
            Costla Green||EX014VI0038|#8BBB2B
            Delivery Yellow||EX014VI0003|#FFE14D
            Drank Purple||EX014VI0019|#76144B
            Durango Blue||EX014VI0026|#00AEDD
            Electric Blue||EX014VI0027|#01619D
            Elephant Pink||EX014VI0013|#FEB4C7
            Exit Green||EX014VI0031|#00A28A
            Fox Red||EX014VI0012|#881014
            Freight Brown||EX014VI0044|#4C3115
            Frog Green||EX014VI0035|#15A43E
            Haze Purple||EX014VI0020|#400155
            Kink Purple||EX014VI0017|#E8B0DA
            Lis Violet||EX014VI0021|#A89AD0
            Lizard Green||EX014VI0039|#6AB36A
            Loyalty Violet||EX014VI0022|#7667BC
            Madrid Red||EX014VI0011|#EB1919
            Palanca Red||EX014VI0010|#D65A5A
            Paradise Pink||EX014VI0016|#8C0C4A
            Piggy Brown||EX014VI0041|#EBC587
            Saint-Denis Green||EX014VI0030|#4FC4BB
            Sashimi||EX014VI0009|#EB9191
            Shredder Grey||EX014VI0045|#E2E3E5
            Skinny Yellow||EX014VI0001|#FFF599
            Sleepless Violet||EX014VI0018|#BA6295
            Smurf Blue||EX014VI0025|#8BCCE0
            Sniper Green||EX014VI0034|#65B62F
            Snoop Blue||EX014VI0028|#004875
            Snotty Green||EX014VI0032|#007056
            Squirtle Green||EX014VI0029|#A0DAC4
            Submarine Yellow||EX014VI0004|#E9B200
            Tasmania Green||EX014VI0036|#123800
            Teddy Brown||EX014VI0042|#DB8F4D
            Thumb Green||EX014VI0040|#006A46
            Tony Orange||EX014VI0007|#E86B11
            Toxic Green||EX014VI0037|#B8E9A6
            Travis Yellow||EX014VI0002|#FFF04D
            Trinidad Green||EX014VI0033|#7BB75F
            Tusi Pink||EX014VI0014|#E87896
            Ursula Violet||EX014VI0023|#15007F
            Vest Orange||EX014VI0006|#EE9225
            Wallaby Brown||EX014VI0043|#875206
            White Lines||EX014VI9010|#FFFFFF
            Wire Grey||EX014VI0046|#9A999F
        """.trimIndent()),
        RawBlock("mtn-water-based", "mtn-montana-colors:mtn-water-based-400", """
            Azo Orange||EX014W2004M|#FF742E
            Azo Orange Deep||EX014W0209M|#F05136
            Azo Orange Light||EX014W0105M|#FF9955
            Azo Yellow Deep||EX014W0177M|#FFB511
            Black Semitransparent||EX014W9311|#A6A6A7
            Blue Green||EX014W0343M|#028DB4
            Blue Green Dark||EX014W0234M|#005476
            Blue Green Deep||EX014W0014M|#00789A
            Blue Green Light||EX014W0342M|#06B5D2
            Blue Green Pale||EX014W0341M|#88CDD3
            Blue Violet||EX014W0225M|#975A71
            Blue Violet Deep||EX014W0167M|#835573
            Blue Violet Light||EX014W0224M|#B985A3
            Brillant Green Deep||EX014W1127M|#255C1E
            Brillant Yellow Green Dark||EX014W0335M|#36792B
            Brillant Yellow Green Deep||EX014W0334M|#569426
            Brillant Yellow Green Light||EX014W0235M|#E6E782
            Brillant Yellow Green Medium||EX014W0333M|#9BBE53
            Brilliant Green||EX014W6018M|#56944F
            Brilliant Light Green||EX014W0034M|#67B346
            Brilliant Yellow Green||EX014W0236M|#CED664
            Burnt Umber||EX014W0266M|#66564F
            Cadmium Red Light||EX014W0223M|#EA746A
            Cadmium Red Pale||EX014W0322M|#F39C9A
            Cadmium Yellow Light||EX014W0222M|#FFE885
            Cadmium Yellow Medium||EX014W1021M|#FFDD35
            Carbon Black||EX014W9011M|#000000
            Carmine||EX014W3004M|#7F2938
            Cerulean Blue||EX014W0217M|#009ECC
            Cobalt Blue||EX014W0068M|#28628E
            Cobalt Blue Light||EX014W0069M|#4492C6
            Cobalt Blue Pale||EX014W0327M|#88C5E4
            Dioxazine Purple||EX014W0173M|#7878A2
            Dioxazine Purple Deep||EX014W0174M|#6C629D
            Dioxazine Purple Light||EX014W0214M|#9185AE
            Dioxazine Purple Pale||EX014W0321M|#BDB5CF
            Emerald Green||EX014W0021M|#00957E
            Emerald Green Light||EX014W0220M|#57B798
            Fluorescent Blue||EX014W0605M|#0099CC
            Fluorescent Fuchsia||EX014W0603M|#FF0095
            Fluorescent Green||EX014W0604M|#5FDD49
            Fluorescent Red||EX014W0602M|#F95951
            Fluorescent Yellow||EX014W0600M|#FFEF39
            Gold-Metal Color||EX014W0127M|#D4AF37
            Grey Green||EX014W0179M|#999675
            Grey Green Dark||EX014W0346M|#4A5D45
            Grey Green Deep||EX014W0131M|#647253
            Grey Green Light||EX014W0345M|#BEC39E
            Naphthol Red||EX014W3020M|#DE4343
            Naphthol Red Deep||EX014W0241M|#CC2219
            Naples Yellow||EX014W0135M|#F4CF81
            Naples Yellow Deep||EX014W0330M|#D7B483
            Neutral Grey||EX014W7040M|#A5AAA8
            Neutral Grey Dark||EX014W7016M|#555357
            Neutral Grey Deep||EX014W0263M|#676C73
            Neutral Grey Light||EX014W7047M|#CCCFD1
            Neutral Grey Pale||EX014W0006M|#D2D7D8
            Phthalo Blue Light||EX014W0029M|#5ECAE8
            Phthalo Green||EX014W0329M|#9CCC95
            Phthalo Green Blue||EX014W0254M|#BBE9DE
            Primary Blue||EX014W0338M|#245BA7
            Primary Blue Deep||EX014W0339M|#23388D
            Primary Blue Light||EX014W0337M|#5388C6
            Primary Blue Pale||EX014W0336M|#5CA5DA
            Prussian Blue||EX014W0030M|#1365A0
            Prussian Blue Deep||EX014W0154M|#005082
            Quinacridone Magenta||EX014W4010M|#D84465
            Quinacridone Rose||EX014W0211M|#EE82A4
            Quinacridone Rose Light||EX014W0323M|#F5AFC5
            Raw Sienna||EX014W0265M|#9D703C
            Raw Umber||EX014W0137M|#B0946F
            Raw Umber Deep||EX014W0139M|#745B48
            Red Violet||EX014W0213M|#A04F65
            Silver-Metal Color||EX014W0126M|#D4D4D4
            Titanium Light||EX014W1013M|#F3DA9A
            Titanium White||EX014W9010M|#FFFFFF
            Turquoise Green||EX014W0219M|#00D2B3
            Ultramarine Blue||EX014W5002M|#385988
            Warm Grey Deep||EX014W0332M|#645C59
            Warm Grey Light||EX014W0302M|#CBC2B0
            Warm Grey Pale||EX014W0331M|#D9D6CF
            White Semitransparent||EX014W9310|#CBCCCD
            Yellow Ocre||EX014W0264M|#BA7F32
        """.trimIndent()),
    )

    val colors: List<OfficialCanColor> by lazy {
        rawBlocks.flatMap { block ->
            block.rows.lineSequence().filter(String::isNotBlank).map { row ->
                val fields = row.split('|', limit = 4)
                OfficialCanColor(
                    lineId = block.lineId,
                    colorName = fields[0],
                    colorCode = fields[1].ifBlank { null },
                    productCode = fields[2].ifBlank { null },
                    hex = fields[3],
                    sourceId = block.sourceId,
                )
            }.toList()
        }
    }

    private val colorsByLine by lazy { colors.groupBy(OfficialCanColor::lineId) }
    private val sourceById by lazy { sources.associateBy(OfficialCanColorSource::id) }

    fun colorsForLine(lineId: String): List<OfficialCanColor> = colorsByLine[lineId].orEmpty()

    fun sourceFor(color: OfficialCanColor): OfficialCanColorSource? = sourceById[color.sourceId]

    fun find(lineId: String?, colorName: String?, colorCode: String?): OfficialCanColor? {
        if (lineId.isNullOrBlank()) return null
        val candidates = colorsForLine(lineId)
        if (candidates.isEmpty()) return null
        val normalizedCode = normalizeCode(colorCode)
        if (normalizedCode.isNotEmpty()) {
            candidates.firstOrNull { color ->
                normalizeCode(color.colorCode) == normalizedCode || normalizeCode(color.productCode) == normalizedCode
            }?.let { return it }
        }
        val normalizedName = normalizeName(colorName)
        if (normalizedName.isEmpty()) return null
        return candidates.firstOrNull { color -> color.nameAliases().any { normalizeName(it) == normalizedName } }
    }

    fun search(lineId: String, query: String, limit: Int = 8): List<OfficialCanColor> {
        val normalizedQuery = normalizeName(query)
        if (normalizedQuery.isEmpty()) return colorsForLine(lineId).take(limit)
        return colorsForLine(lineId).asSequence().mapNotNull { color ->
            val aliases = color.nameAliases().map(::normalizeName)
            val rank = when {
                aliases.any { it == normalizedQuery } -> 0
                aliases.any { it.startsWith(normalizedQuery) } -> 1
                aliases.any { it.contains(normalizedQuery) } -> 2
                else -> return@mapNotNull null
            }
            color to rank
        }.sortedWith(compareBy<Pair<OfficialCanColor, Int>> { it.second }.thenBy { it.first.colorName }).take(limit).map { it.first }.toList()
    }

    private fun OfficialCanColor.nameAliases(): List<String> = buildList {
        add(colorName)
        colorCode?.let { code ->
            add("$code $colorName")
            code.replace(Regex("[0-9#\\s-]+$"), "").trim().takeIf(String::isNotBlank)?.let { add("$it $colorName") }
        }
    }

    private fun normalizeName(value: String?): String = Normalizer.normalize(value.orEmpty(), Normalizer.Form.NFKD)
        .replace(Regex("\\p{M}+"), "")
        .lowercase()
        .replace(Regex("[^a-z0-9]+"), " ")
        .trim()

    private fun normalizeCode(value: String?): String = value.orEmpty().lowercase().replace(Regex("[^a-z0-9#]+"), "")
}
